-- Variables initialization
-- init some local variables
_var = {
    client = {},
    menu = {},
    vehicle = {}
}
_var.client.isStaffModeActivated = false
_var.client.staffGroup = nil
_var.menu.isOpened = false
_var.menu.bannerTexture = nil
_var.vehicle.doorArrayIndex = 1
_var.vehicle.doorArray = {
	_("door_frontleft"),
	_("door_frontright"),
	_("door_backleft"),
	_("door_backright"),
	_("door_hood"),
	_("door_trunk"),
	_("door_all"),
}
_var.vehicle.paintColors = {
	[0] = "Black",
	[1] = "Graphite",
	[2] = "Black Steel",
	[3] = "Dark Steel",
	[4] = "Silver",
	[5] = "Bluish Silver",
	[6] = "Rolled Steel",
	[7] = "Shadow Silver",
	[8] = "Stone Silver",
	[9] = "Midnight Silver",
	[10] = "Cast Iron Silver",
	[11] = "Anhracite Black",
	[12] = "Black",
	[13] = "Gray",
	[14] = "Light Gray",
	[27] = "Red",
	[28] = "Torino Red",
	[29] = "Formula Red",
	[30] = "Blaze Red",
	[31] = "Grace Red",
	[32] = "Garnet Red",
	[33] = "Sunset Red",
	[34] = "Cabernet Red",
	[35] = "Candy Red",
	[36] = "Sunrise Orange",
	[38] = "Orange",
	[39] = "Red",
	[40] = "Dark Red",
	[41] = "Orange",
	[42] = "Yellow",
	[49] = "Dark Green",
	[50] = "Racing Green",
	[51] = "Sea Green",
	[52] = "Olive Green",
	[53] = "Bright Green",
	[54] = "Gasoline Green",
	[55] = "Lime Green",
	[61] = "Galaxy Blue",
	[62] = "Dark Blue",
	[63] = "Saxon Blue",
	[64] = "Blue",
	[65] = "Mariner Blue",
	[66] = "Harbor Blue",
	[67] = "Diamond Blue",
	[68] = "Surf Blue",
	[69] = "Nautical Blue",
	[70] = "Ultra Blue",
	[71] = "Schafter Purple",
	[72] = "Spinnaker Purple",
	[73] = "Racing Blue",
	[74] = "Light Blue",
	[82] = "Dark Blue",
	[83] = "Blue",
	[84] = "Midnight Blue",
	[88] = "Yellow",
	[89] = "Race Yellow",
	[90] = "Bronze",
	[91] = "Dew Yellow",
	[92] = "Lime Green",
	[94] = "Feltzer Brown",
	[95] = "Creeen Brown",
	[96] = "Chocolate Brown",
	[97] = "Maple Brown",
	[98] = "Saddle Brown",
	[99] = "Straw Brown",
	[100] = "Moss Brown",
	[101] = "Bison Brown",
	[102] = "Woodbeech Brown",
	[103] = "Beechwood Brown",
	[104] = "Sienna Brown",
	[105] = "Sandy Brown",
	[106] = "Bleached Brown",
	[107] = "Cream",
	[111] = "Ice White",
	[112] = "Frost White",
	[120] = "Chrome",
	[128] = "Green",
	[131] = "Ice White",
	[135] = "Hot Pink",
	[136] = "Salmon Pink",
	[137] = "Pfsiter Pink",
	[138] = "Bright Orange",
	[141] = "Midnight Blue",
	[142] = "Midnight Purple",
	[143] = "Wine Red",
	[145] = "Bright Purple",
	[147] = "Carbon Black",
	[148] = "Schafter Purple",
	[149] = "Midnight Purple",
	[150] = "Lava Red",
	[151] = "Forest Green",
	[152] = "Olive Darb",
	[153] = "Dark Earth",
	[154] = "Desert Tan",
	[155] = "Foliage Green",
}
