-- Variables initialization
-- init some local variables
_var = {
	client = {},
	menu = {},
	activeThreads = {},
	vehicle = {},
	reports = {},
}
_var.client.isStaffModeActivated = false
_var.client.staffGroup = nil
_var.client.playerData = {}
_var.client.userData = {}
_var.reports.list = {}
_var.reports.count = 0
_var.reports.countHiden = 0
_var.reports.selectedReport = 1
_var.menu.cooldownStatus = false
_var.menu.isOpened = false
_var.menu.bannerTexture = nil
_var.menu.reportsFilterArrayIndex = 1
_var.menu.reportsFilterArray = {
	_("main_reports_filter_all"),
	_("main_reports_filter_waiting"),
	_("main_reports_filter_taken"),
}
_var.menu.favritesActionsArrayIndex = 1
_var.menu.favritesActionsArray = {
	_("main_vehicles_favorites_interact_spawn"),
	_("main_vehicles_favorites_interact_delete"),
}
_var.menu.searchVehicle = ""
_var.menu.findedVehicle = nil
_var.activeThreads.getVehiclesFavorites = false
_var.activeThreads.getReports = false
_var.vehicle.doorArrayIndex = 1
_var.vehicle.doorArray = {
	_("door_frontleft"),
	_("door_frontright"),
	_("door_backleft"),
	_("door_backright"),
	_("door_hood"),
	_("door_trunk"),
	_("door_all"),
}
_var.vehicle.paintColorsArrayIndexMain = 1
_var.vehicle.paintColorsArrayIndexSecondary = 1
_var.vehicle.paintColors = {
	{ "Chrome", 120 },
	{ "Black", 0 },
	{ "Carbon Black", 147 },
	{ "Graphite", 1 },
	{ "Anhracite Black", 11 },
	{ "Black Steel", 2 },
	{ "Dark Steel", 3 },
	{ "Silver", 4 },
	{ "Bluish Silver", 5 },
	{ "Rolled Steel", 6 },
	{ "Shadow Silver", 7 },
	{ "Stone Silver", 8 },
	{ "Midnight Silver", 9 },
	{ "Cast Iron Silver", 10 },
	{ "Red", 27 },
	{ "Torino Red", 28 },
	{ "Formula Red", 29 },
	{ "Lava Red", 150 },
	{ "Blaze Red", 30 },
	{ "Grace Red", 31 },
	{ "Garnet Red", 32 },
	{ "Sunset Red", 33 },
	{ "Cabernet Red", 34 },
	{ "Wine Red", 143 },
	{ "Candy Red", 35 },
	{ "Hot Pink", 135 },
	{ "Pfsiter Pink", 137 },
	{ "Salmon Pink", 136 },
	{ "Sunrise Orange", 36 },
	{ "Orange", 38 },
	{ "Bright Orange", 138 },
	{ "Gold", 99 },
	{ "Bronze", 90 },
	{ "Yellow", 88 },
	{ "Race Yellow", 89 },
	{ "Dew Yellow", 91 },
	{ "Dark Green", 49 },
	{ "Racing Green", 50 },
	{ "Sea Green", 51 },
	{ "Olive Green", 52 },
	{ "Bright Green", 53 },
	{ "Gasoline Green", 54 },
	{ "Lime Green", 92 },
	{ "Midnight Blue", 141 },
	{ "Galaxy Blue", 61 },
	{ "Dark Blue", 62 },
	{ "Saxon Blue", 63 },
	{ "Blue", 64 },
	{ "Mariner Blue", 65 },
	{ "Harbor Blue", 66 },
	{ "Diamond Blue", 67 },
	{ "Surf Blue", 68 },
	{ "Nautical Blue", 69 },
	{ "Racing Blue", 73 },
	{ "Ultra Blue", 70 },
	{ "Light Blue", 74 },
	{ "Chocolate Brown", 96 },
	{ "Bison Brown", 101 },
	{ "Creeen Brown", 95 },
	{ "Feltzer Brown", 94 },
	{ "Maple Brown", 97 },
	{ "Beechwood Brown", 103 },
	{ "Sienna Brown", 104 },
	{ "Saddle Brown", 98 },
	{ "Moss Brown", 100 },
	{ "Woodbeech Brown", 102 },
	{ "Straw Brown", 99 },
	{ "Sandy Brown", 105 },
	{ "Bleached Brown", 106 },
	{ "Schafter Purple", 71 },
	{ "Spinnaker Purple", 72 },
	{ "Midnight Purple", 142 },
	{ "Bright Purple", 145 },
	{ "Cream", 107 },
	{ "Ice White", 111 },
	{ "Frost White", 112 },
	{ "Black", 12 },
	{ "Gray", 13 },
	{ "Light Gray", 14 },
	{ "Ice White", 131 },
	{ "Blue", 83 },
	{ "Dark Blue", 82 },
	{ "Midnight Blue", 84 },
	{ "Midnight Purple", 149 },
	{ "Schafter Purple", 148 },
	{ "Red", 39 },
	{ "Dark Red", 40 },
	{ "Orange", 41 },
	{ "Yellow", 42 },
	{ "Lime Green", 55 },
	{ "Green", 128 },
	{ "Forest Green", 151 },
	{ "Foliage Green", 155 },
	{ "Olive Darb", 152 },
	{ "Dark Earth", 153 },
	{ "Desert Tan", 154 },
}
_var.vehicle.paintColorsArray = {}
for _, color in pairs(_var.vehicle.paintColors) do
	table.insert(_var.vehicle.paintColorsArray, color[1])
end
_var.vehicle.boostArrayIndex = 1
_var.vehicle.boostArray = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 }
_var.vehicle.list = {
	{ type = "Service", model = "airbus", label = "Airbus" },
	{ type = "Service", model = "brickade", label = "Brickade" },
	{ type = "Service", model = "bus", label = "Bus" },
	{ type = "Service", model = "coach", label = "Coach" },
	{ type = "Service", model = "rallytruck", label = "Rally Truck" },
	{ type = "Service", model = "rentalBus", label = "Rental Bus" },
	{ type = "Service", model = "taxi", label = "Taxi" },
	{ type = "Service", model = "tourbus", label = "Tour Bus" },
	{ type = "Service", model = "trash", label = "Trash" },
	{ type = "Service", model = "trash2", label = "Trash 2" },
	{ type = "Planes", model = "besra", label = "Besra" },
	{ type = "Planes", model = "blimp", label = "Blimp" },
	{ type = "Planes", model = "blimp2", label = "Blimp 2" },
	{ type = "Planes", model = "cargoPlane", label = "Cargo Plane" },
	{ type = "Planes", model = "cuban800", label = "Cuban800" },
	{ type = "Planes", model = "dodo", label = "Dodo" },
	{ type = "Planes", model = "duster", label = "Duster" },
	{ type = "Planes", model = "hydra", label = "Hydra" },
	{ type = "Planes", model = "jet", label = "Jet" },
	{ type = "Planes", model = "lazer", label = "Lazer" },
	{ type = "Planes", model = "luxor", label = "Luxor" },
	{ type = "Planes", model = "luxor2", label = "Luxor 2" },
	{ type = "Planes", model = "mammatus", label = "Mammatus" },
	{ type = "Planes", model = "miljet", label = "Miljet" },
	{ type = "Planes", model = "nimbus", label = "Nimbus" },
	{ type = "Planes", model = "shamal", label = "Shamal" },
	{ type = "Planes", model = "stunt", label = "Stunt" },
	{ type = "Planes", model = "titan", label = "Titan" },
	{ type = "Planes", model = "velum", label = "Velum" },
	{ type = "Planes", model = "velum2", label = "Velum2" },
	{ type = "Planes", model = "vestra", label = "Vestra" },
	{ type = "Military", model = "apc", label = "APC" },
	{ type = "Military", model = "barracks", label = "Barracks" },
	{ type = "Military", model = "barracks2", label = "Barracks 2" },
	{ type = "Military", model = "barracks3", label = "Barracks 3" },
	{ type = "Military", model = "crusader", label = "Crusader" },
	{ type = "Military", model = "halftrack", label = "Half Track" },
	{ type = "Military", model = "rhino", label = "Rhino" },
	{ type = "Industrials", model = "bulldozer", label = "Bulldozer" },
	{ type = "Industrials", model = "cutter", label = "Cutter" },
	{ type = "Industrials", model = "dump", label = "Dump" },
	{ type = "Industrials", model = "flatbed", label = "Flatbed" },
	{ type = "Industrials", model = "guardian", label = "Guardian" },
	{ type = "Industrials", model = "handler", label = "Handler" },
	{ type = "Industrials", model = "mixer", label = "Mixer" },
	{ type = "Industrials", model = "mixer2", label = "Mixer2" },
	{ type = "Industrials", model = "rubble", label = "Rubble" },
	{ type = "Industrials", model = "tipTruck", label = "TipTruck" },
	{ type = "Industrials", model = "tipTruck2", label = "TipTruck2" },
	{ type = "Helicopters", model = "annihilator", label = "Annihilator" },
	{ type = "Helicopters", model = "buzzard", label = "Buzzard" },
	{ type = "Helicopters", model = "buzzard2", label = "Buzzard 2" },
	{ type = "Helicopters", model = "cargobob", label = "Cargobob" },
	{ type = "Helicopters", model = "cargobob2", label = "Cargobob 2" },
	{ type = "Helicopters", model = "cargobob3", label = "Cargobob 3" },
	{ type = "Helicopters", model = "cargobob4", label = "Cargobob 4" },
	{ type = "Helicopters", model = "frogger", label = "Frogger" },
	{ type = "Helicopters", model = "frogger2", label = "Frogger 2" },
	{ type = "Helicopters", model = "maverick", label = "Maverick" },
	{ type = "Helicopters", model = "savage", label = "Savage" },
	{ type = "Helicopters", model = "skylift", label = "Skylift" },
	{ type = "Helicopters", model = "supervolito", label = "Super Volito" },
	{ type = "Helicopters", model = "supervolito2", label = "Super Volito 2" },
	{ type = "Helicopters", model = "swift", label = "Swift" },
	{ type = "Helicopters", model = "swift2", label = "Swift 2" },
	{ type = "Helicopters", model = "valkyrie", label = "Valkyrie" },
	{ type = "Helicopters", model = "valkyrie2", label = "Valkyrie 2" },
	{ type = "Helicopters", model = "volatus", label = "Volatus 2" },
	{ type = "Emergency", model = "ambulance", label = "Ambulance" },
	{ type = "Emergency", model = "fbi", label = "FBI" },
	{ type = "Emergency", model = "fbi2", label = "FBI 2" },
	{ type = "Emergency", model = "firetruck", label = "Fire Truck" },
	{ type = "Emergency", model = "pbus", label = "Police Bus" },
	{ type = "Emergency", model = "police", label = "Police" },
	{ type = "Emergency", model = "police2", label = "Police 2" },
	{ type = "Emergency", model = "police3", label = "Police 3" },
	{ type = "Emergency", model = "police4", label = "Police 4" },
	{ type = "Emergency", model = "policeold1", label = "PoliceOld1" },
	{ type = "Emergency", model = "policeold2", label = "PoliceOld 2" },
	{ type = "Emergency", model = "policeT", label = "PoliceT" },
	{ type = "Emergency", model = "policeb", label = "Policeb" },
	{ type = "Emergency", model = "polmav", label = "Polmav" },
	{ type = "Emergency", model = "pranger", label = "Pranger" },
	{ type = "Emergency", model = "predator", label = "Predator" },
	{ type = "Emergency", model = "riot", label = "Riot" },
	{ type = "Emergency", model = "sheriff", label = "Sheriff" },
	{ type = "Emergency", model = "sheriff2", label = "Sheriff 2" },
	{ type = "Boats", model = "dinghy", label = "Dinghy" },
	{ type = "Boats", model = "dinghy2", label = "Dinghy 2" },
	{ type = "Boats", model = "dinghy3", label = "Dinghy 3" },
	{ type = "Boats", model = "dinghy4", label = "Dinghy 4" },
	{ type = "Boats", model = "jetmax", label = "Jet Max" },
	{ type = "Boats", model = "marquis", label = "Marquis" },
	{ type = "Boats", model = "seashark", label = "Seashark" },
	{ type = "Boats", model = "seashark2", label = "Seashark 2" },
	{ type = "Boats", model = "seashark3", label = "Seashark 3" },
	{ type = "Boats", model = "speeder", label = "Speeder" },
	{ type = "Boats", model = "speeder2", label = "Speeder 2" },
	{ type = "Boats", model = "squalo", label = "Squalo" },
	{ type = "Boats", model = "submersible", label = "Sub Mersible" },
	{ type = "Boats", model = "submersible2", label = "Sub Mersible 2" },
	{ type = "Boats", model = "suntrap", label = "Sun Trap" },
	{ type = "Boats", model = "toro", label = "Toro" },
	{ type = "Boats", model = "toro2", label = "Toro 2" },
	{ type = "Boats", model = "tropic", label = "Tropic" },
	{ type = "Boats", model = "tropic2", label = "Tropic 2" },
	{ type = "Boats", model = "tug", label = "Tug" },
	{ type = "Commercials", model = "Benson", label = "Benson" },
	{ type = "Commercials", model = "Biff", label = "Biff" },
	{ type = "Commercials", model = "Hauler", label = "Hauler" },
	{ type = "Commercials", model = "Hauler2", label = "Hauler 2" },
	{ type = "Commercials", model = "Mule", label = "Mule" },
	{ type = "Commercials", model = "Mule2", label = "Mule 2" },
	{ type = "Commercials", model = "Mule3", label = "Mule 3" },
	{ type = "Commercials", model = "Packer", label = "Packer" },
	{ type = "Commercials", model = "Phantom", label = "Phantom" },
	{ type = "Commercials", model = "Phantom2", label = "Phantom 2" },
	{ type = "Commercials", model = "Phantom3", label = "Phantom 3" },
	{ type = "Commercials", model = "Pounder", label = "Pounder" },
	{ type = "Commercials", model = "Stockade", label = "Stockade" },
	{ type = "Commercials", model = "Stockade3", label = "Stockade 3" },
	{ type = "Compacts", model = "asbo", label = "Asbo" },
	{ type = "Compacts", model = "blista", label = "Blista" },
	{ type = "Compacts", model = "brioso", label = "Brioso" },
	{ type = "Compacts", model = "brioso2", label = "Brioso 2" },
	{ type = "Compacts", model = "club", label = "Club" },
	{ type = "Compacts", model = "dilettante", label = "Dilettante" },
	{ type = "Compacts", model = "dilettante2", label = "Dilettante2" },
	{ type = "Compacts", model = "issi2", label = "Issi 2" },
	{ type = "Compacts", model = "issi3", label = "Issi 3" },
	{ type = "Compacts", model = "issi5", label = "Issi 5" },
	{ type = "Compacts", model = "kanjo", label = "Kanjo" },
	{ type = "Compacts", model = "panto", label = "Panto" },
	{ type = "Compacts", model = "prairie", label = "Prairie" },
	{ type = "Compacts", model = "rhapsody", label = "Rhapsody" },
	{ type = "Compacts", model = "weevil", label = "Weevil" },
	{ type = "Coupes", model = "cogcabrio", label = "Cognoscenti Cabrio" },
	{ type = "Coupes", model = "exemplar", label = "Exemplar" },
	{ type = "Coupes", model = "f620", label = "F620" },
	{ type = "Coupes", model = "felon", label = "Felon" },
	{ type = "Coupes", model = "felon2", label = "Felon 2" },
	{ type = "Coupes", model = "jackal", label = "Jackal" },
	{ type = "Coupes", model = "oracle", label = "Oracle" },
	{ type = "Coupes", model = "oracle2", label = "Oracle 2" },
	{ type = "Coupes", model = "prairie", label = "Prairie" },
	{ type = "Coupes", model = "previon", label = "Previon" },
	{ type = "Coupes", model = "sentinel", label = "Sentinel" },
	{ type = "Coupes", model = "sentinel2", label = "Sentinel2" },
	{ type = "Coupes", model = "windsor", label = "Windsor" },
	{ type = "Coupes", model = "windsor2", label = "Windsor 2" },
	{ type = "Coupes", model = "zion", label = "Zion" },
	{ type = "Coupes", model = "zion2", label = "Zion 2" },
	{ type = "Sedans", model = "asea", label = "Asea" },
	{ type = "Sedans", model = "asea2", label = "Asea2" },
	{ type = "Sedans", model = "asterope", label = "Asterope" },
	{ type = "Sedans", model = "cog55", label = "Cognoscenti 55" },
	{ type = "Sedans", model = "cognoscenti", label = "Cognoscenti" },
	{ type = "Sedans", model = "emperor", label = "Emperor" },
	{ type = "Sedans", model = "emperor2", label = "Emperor 2" },
	{ type = "Sedans", model = "emperor3", label = "Emperor 3" },
	{ type = "Sedans", model = "fugitive", label = "Fugitive" },
	{ type = "Sedans", model = "glendale", label = "Glendale" },
	{ type = "Sedans", model = "glendale2", label = "Glendale 2" },
	{ type = "Sedans", model = "ingot", label = "Ingot" },
	{ type = "Sedans", model = "intruder", label = "Intruder" },
	{ type = "Sedans", model = "premier", label = "Premier" },
	{ type = "Sedans", model = "primo", label = "Primo" },
	{ type = "Sedans", model = "primo2", label = "Primo Custom" },
	{ type = "Sedans", model = "regina", label = "Regina" },
	{ type = "Sedans", model = "stafford", label = "Stafford" },
	{ type = "Sedans", model = "stanier", label = "Stanier" },
	{ type = "Sedans", model = "stratum", label = "Stratum" },
	{ type = "Sedans", model = "stretch", label = "Stretch" },
	{ type = "Sedans", model = "Superd", label = "Superd" },
	{ type = "Sedans", model = "surge", label = "Surge" },
	{ type = "Sedans", model = "tailgater", label = "Tailgater" },
	{ type = "Sedans", model = "tailgater2", label = "Tailgater2" },
	{ type = "Sedans", model = "warrener", label = "Warrener" },
	{ type = "Sedans", model = "washington", label = "Washington" },
	{ type = "Sports", model = "alpha", label = "Alpha" },
	{ type = "Sports", model = "banshee", label = "Banshee" },
	{ type = "Sports", model = "bestiagts", label = "Bestia GTS" },
	{ type = "Sports", model = "blista2", label = "Blista 2" },
	{ type = "Sports", model = "blista3", label = "Blista 3" },
	{ type = "Sports", model = "buffalo", label = "Buffalo" },
	{ type = "Sports", model = "buffalo2", label = "Buffalo Customs" },
	{ type = "Sports", model = "buffalo3", label = "Buffalo Sport" },
	{ type = "Sports", model = "carbonizzare", label = "Carbonizzare" },
	{ type = "Sports", model = "comet2", label = "Comet 2" },
	{ type = "Sports", model = "comet3", label = "Comet 3" },
	{ type = "Sports", model = "comet4", label = "Comet 4" },
	{ type = "Sports", model = "comet5", label = "Comet 5" },
	{ type = "Sports", model = "comet6", label = "Comet 6" },
	{ type = "Sports", model = "coquette", label = "Coquette" },
	{ type = "Sports", model = "coquette4", label = "Coquette 4" },
	{ type = "Sports", model = "cypher", label = "Cypher" },
	{ type = "Sports", model = "calico", label = "Calico" },
	{ type = "Sports", model = "drafter", label = "Drafter" },
	{ type = "Sports", model = "deveste", label = "Deveste" },
	{ type = "Sports", model = "elegy", label = "Elegy Retro" },
	{ type = "Sports", model = "elegy2", label = "Elegy" },
	{ type = "Sports", model = "euros", label = "Euros" },
	{ type = "Sports", model = "feltzer2", label = "Feltzer 2" },
	{ type = "Sports", model = "flashgt", label = "Flash GT" },
	{ type = "Sports", model = "furoregt", label = "Furore GT" },
	{ type = "Sports", model = "fusilade", label = "Fusilade" },
	{ type = "Sports", model = "futo", label = "Futo" },
	{ type = "Sports", model = "futo2", label = "Futo 2" },
	{ type = "Sports", model = "gb200", label = "GB200" },
	{ type = "Sports", model = "growler", label = "Growler" },
	{ type = "Sports", model = "hotring", label = "Hotring" },
	{ type = "Sports", model = "komoda", label = "Komoda" },
	{ type = "Sports", model = "imorgon", label = "Imorgon" },
	{ type = "Sports", model = "issi7", label = "Issi 7" },
	{ type = "Sports", model = "italigto", label = "Itali GTO" },
	{ type = "Sports", model = "italirsx", label = "Itali RSX" },
	{ type = "Sports", model = "jugular", label = "Jugular" },
	{ type = "Sports", model = "jester", label = "Jester" },
	{ type = "Sports", model = "jester2", label = "Jester 2" },
	{ type = "Sports", model = "jester3", label = "Jester 3" },
	{ type = "Sports", model = "jester4", label = "Jester 4" },
	{ type = "Sports", model = "khamelion", label = "Khamelion" },
	{ type = "Sports", model = "kuruma", label = "Kuruma" },
	{ type = "Sports", model = "locust", label = "Locust" },
	{ type = "Sports", model = "lynx", label = "Lynx" },
	{ type = "Sports", model = "massacro", label = "Massacro" },
	{ type = "Sports", model = "massacro2", label = "Massacro 2" },
	{ type = "Sports", model = "neo", label = "Neo" },
	{ type = "Sports", model = "neon", label = "Neon" },
	{ type = "Sports", model = "ninef", label = "Ninef" },
	{ type = "Sports", model = "ninef2", label = "Ninef 2" },
	{ type = "Sports", model = "omnis", label = "Omnis" },
	{ type = "Sports", model = "paragon", label = "Paragon" },
	{ type = "Sports", model = "paragon2", label = "Paragon 2" },
	{ type = "Sports", model = "pariah", label = "Pariah" },
	{ type = "Sports", model = "penumbra", label = "Penumbra" },
	{ type = "Sports", model = "penumbra2", label = "Penumbra 2" },
	{ type = "Sports", model = "raiden", label = "Raiden" },
	{ type = "Sports", model = "rapidgt", label = "Rapid GT" },
	{ type = "Sports", model = "rapidgt2", label = "Rapid GT2" },
	{ type = "Sports", model = "raptor", label = "Raptor" },
	{ type = "Sports", model = "revolter", label = "Revolter" },
	{ type = "Sports", model = "ruston", label = "Ruston" },
	{ type = "Sports", model = "rt3000", label = "RT3000" },
	{ type = "Sports", model = "remus", label = "Remus" },
	{ type = "Sports", model = "schafter2", label = "Schafter 2" },
	{ type = "Sports", model = "schafter3", label = "Schafter 3" },
	{ type = "Sports", model = "schafter4", label = "Schafter 4" },
	{ type = "Sports", model = "schlagen", label = "Schlagen" },
	{ type = "Sports", model = "schwarzer", label = "Schwarzer" },
	{ type = "Sports", model = "sentinel3", label = "Sentine l3" },
	{ type = "Sports", model = "seven70", label = "Seven 70" },
	{ type = "Sports", model = "specter", label = "Specter" },
	{ type = "Sports", model = "specter2", label = "Specter 2" },
	{ type = "Sports", model = "streiter", label = "Streiter" },
	{ type = "Sports", model = "sugoi", label = "Sugoi" },
	{ type = "Sports", model = "sultan", label = "Sultan" },
	{ type = "Sports", model = "sultan2", label = "Sultan Classic" },
	{ type = "Sports", model = "sultan3", label = "Sultan 3" },
	{ type = "Sports", model = "surano", label = "Surano" },
	{ type = "Sports", model = "tampa2", label = "Tampa 2" },
	{ type = "Sports", model = "tropos", label = "Tropos" },
	{ type = "Sports", model = "verlierer2", label = "Verlierer 2" },
	{ type = "Sports", model = "vstr", label = "VSTR" },
	{ type = "Sports", model = "vectre", label = "Vectre" },
	{ type = "Sports", model = "zr350", label = "ZR350" },
	{ type = "Sports Classic", model = "ardent", label = "Ardent" },
	{ type = "Sports Classic", model = "btype", label = "Btype" },
	{ type = "Sports Classic", model = "btype2", label = "Btype 2" },
	{ type = "Sports Classic", model = "btype3", label = "Btype 3" },
	{ type = "Sports Classic", model = "casco", label = "Casco" },
	{ type = "Sports Classic", model = "cheetah2", label = "Cheetah 2" },
	{ type = "Sports Classic", model = "coquette2", label = "Coquette 2" },
	{ type = "Sports Classic", model = "cheburek", label = "Cheburek" },
	{ type = "Sports Classic", model = "dynasty", label = "Dynasty" },
	{ type = "Sports Classic", model = "fagaloa", label = "Fagaloa" },
	{ type = "Sports Classic", model = "feltzer3", label = "Feltzer 3" },
	{ type = "Sports Classic", model = "gt500", label = "GT500" },
	{ type = "Sports Classic", model = "infernus2", label = "Infernus 2" },
	{ type = "Sports Classic", model = "jb700", label = "JB700" },
	{ type = "Sports Classic", model = "jb7002", label = "JB700 2" },
	{ type = "Sports Classic", model = "mamba", label = "Mamba" },
	{ type = "Sports Classic", model = "manana", label = "Manana" },
	{ type = "Sports Classic", model = "manana2", label = "Manana 2" },
	{ type = "Sports Classic", model = "michelli", label = "Michelli" },
	{ type = "Sports Classic", model = "monroe", label = "Monroe" },
	{ type = "Sports Classic", model = "nebula", label = "Nebula" },
	{ type = "Sports Classic", model = "peyote", label = "Peyote" },
	{ type = "Sports Classic", model = "peyote3", label = "Peyote 3" },
	{ type = "Sports Classic", model = "pigalle", label = "Pigalle" },
	{ type = "Sports Classic", model = "rapidgt3", label = "Rapid GT3" },
	{ type = "Sports Classic", model = "retinue", label = "Retinue" },
	{ type = "Sports Classic", model = "retinue2", label = "Retinue 2" },
	{ type = "Sports Classic", model = "savestra", label = "Savestra" },
	{ type = "Sports Classic", model = "stinger", label = "Stinger" },
	{ type = "Sports Classic", model = "stingergt", label = "Stingergt" },
	{ type = "Sports Classic", model = "stromberg", label = "Stromberg" },
	{ type = "Sports Classic", model = "swinger", label = "Swinger" },
	{ type = "Sports Classic", model = "torero", label = "Torero" },
	{ type = "Sports Classic", model = "tornado", label = "Tornado" },
	{ type = "Sports Classic", model = "tornado2", label = "Tornado 2" },
	{ type = "Sports Classic", model = "tornado3", label = "Tornado 3" },
	{ type = "Sports Classic", model = "tornado4", label = "Tornado 4" },
	{ type = "Sports Classic", model = "tornado5", label = "Tornado 5" },
	{ type = "Sports Classic", model = "tornado6", label = "Tornado 6" },
	{ type = "Sports Classic", model = "toreador", label = "Toreador" },
	{ type = "Sports Classic", model = "turismo2", label = "Turismo 2" },
	{ type = "Sports Classic", model = "viseris", label = "Viseris" },
	{ type = "Sports Classic", model = "z190", label = "Z190" },
	{ type = "Sports Classic", model = "ztype", label = "Ztype" },
	{ type = "Sports Classic", model = "zion3", label = "Zion 3" },
	{ type = "Super", model = "adder", label = "Adder" },
	{ type = "Super", model = "autarch", label = "Autarch" },
	{ type = "Super", model = "banshee2", label = "Banshee 2" },
	{ type = "Super", model = "bullet", label = "Bullet" },
	{ type = "Super", model = "cheetah", label = "Cheetah" },
	{ type = "Super", model = "cyclone", label = "Cyclone" },
	{ type = "Super", model = "entity2", label = "Entity2" },
	{ type = "Super", model = "entityxf", label = "Entity XF" },
	{ type = "Super", model = "emerus", label = "Emerus" },
	{ type = "Super", model = "fmj", label = "FMJ" },
	{ type = "Super", model = "furia", label = "Furia" },
	{ type = "Super", model = "gp1", label = "GP 1" },
	{ type = "Super", model = "infernus", label = "Infernus" },
	{ type = "Super", model = "italigtb", label = "Itali GTB" },
	{ type = "Super", model = "italigtb2", label = "Itali GTB2" },
	{ type = "Super", model = "krieger", label = "Krieger" },
	{ type = "Super", model = "le7b", label = "LE7b" },
	{ type = "Super", model = "nero", label = "Nero" },
	{ type = "Super", model = "nero2", label = "Nero 2" },
	{ type = "Super", model = "osiris", label = "Osiris" },
	{ type = "Super", model = "penetrator", label = "Penetrator" },
	{ type = "Super", model = "pfister811", label = "Pfister 811" },
	{ type = "Super", model = "prototipo", label = "Prototipo" },
	{ type = "Super", model = "reaper", label = "Reaper" },
	{ type = "Super", model = "s80", label = "S80" },
	{ type = "Super", model = "sc1", label = "SC1" },
	{ type = "Super", model = "sheava", label = "Sheava" },
	{ type = "Super", model = "sultanrs", label = "Sultan RS" },
	{ type = "Super", model = "t20", label = "T20" },
	{ type = "Super", model = "taipan", label = "Taipan" },
	{ type = "Super", model = "tempesta", label = "Tempesta" },
	{ type = "Super", model = "tezeract", label = "Tezeract" },
	{ type = "Super", model = "thrax", label = "Thrax" },
	{ type = "Super", model = "tigon", label = "Tigon" },
	{ type = "Super", model = "turismor", label = "Turismo R" },
	{ type = "Super", model = "tyrant", label = "Tyrant" },
	{ type = "Super", model = "tyrus", label = "Tyrus" },
	{ type = "Super", model = "vacca", label = "Vacca" },
	{ type = "Super", model = "vagner", label = "Vagner" },
	{ type = "Super", model = "visione", label = "Visione" },
	{ type = "Super", model = "voltic", label = "Voltic" },
	{ type = "Super", model = "xa21", label = "XA21" },
	{ type = "Super", model = "zentorno", label = "Zentorno" },
	{ type = "Super", model = "zorrusso", label = "Zorrusso" },
	{ type = "Muscle", model = "blade", label = "Blade" },
	{ type = "Muscle", model = "buccaneer", label = "Buccaneer" },
	{ type = "Muscle", model = "buccaneer2", label = "Buccaneer 2" },
	{ type = "Muscle", model = "chino", label = "Chino" },
	{ type = "Muscle", model = "chino2", label = "Chino 2" },
	{ type = "Muscle", model = "clique", label = "Clique" },
	{ type = "Muscle", model = "coquette3", label = "Coquette 3" },
	{ type = "Muscle", model = "deviant", label = "Deviant" },
	{ type = "Muscle", model = "dominator", label = "Dominator" },
	{ type = "Muscle", model = "dominator2", label = "Dominator 2" },
	{ type = "Muscle", model = "dominator3", label = "Dominator 3" },
	{ type = "Muscle", model = "dukes", label = "Dukes" },
	{ type = "Muscle", model = "dukes3", label = "Dukes 3" },
	{ type = "Muscle", model = "dominator7", label = "Dominator 7" },
	{ type = "Muscle", model = "faction", label = "Faction" },
	{ type = "Muscle", model = "faction2", label = "Faction 2" },
	{ type = "Muscle", model = "faction3", label = "Faction 3" },
	{ type = "Muscle", model = "ellie", label = "Ellie" },
	{ type = "Muscle", model = "gauntlet", label = "Gauntlet" },
	{ type = "Muscle", model = "gauntlet2", label = "Gauntlet 2" },
	{ type = "Muscle", model = "gauntlet3", label = "Gauntlet 3" },
	{ type = "Muscle", model = "gauntlet4", label = "Gauntlet 4" },
	{ type = "Muscle", model = "gauntlet5", label = "Gauntlet 5" },
	{ type = "Muscle", model = "hermes", label = "Hermes" },
	{ type = "Muscle", model = "hotknife", label = "Hotknife" },
	{ type = "Muscle", model = "hustler", label = "Hustler" },
	{ type = "Muscle", model = "impaler", label = "Impaler" },
	{ type = "Muscle", model = "impaler2", label = "Impaler 2" },
	{ type = "Muscle", model = "impaler3", label = "Impaler 3" },
	{ type = "Muscle", model = "impaler4", label = "Impaler 4" },
	{ type = "Muscle", model = "imperator", label = "Imperator" },
	{ type = "Muscle", model = "imperator2", label = "Imperator 2" },
	{ type = "Muscle", model = "lurcher", label = "Lurcher" },
	{ type = "Muscle", model = "moonbeam", label = "Moonbeam" },
	{ type = "Muscle", model = "moonbeam2", label = "Moonbeam 2" },
	{ type = "Muscle", model = "nightshade", label = "Nightshade" },
	{ type = "Muscle", model = "peyote2", label = "Peyote 2" },
	{ type = "Muscle", model = "phoenix", label = "Phoenix" },
	{ type = "Muscle", model = "picador", label = "Picador" },
	{ type = "Muscle", model = "ratloader", label = "Rat Loader" },
	{ type = "Muscle", model = "ratloader2", label = "Rat Loader 2" },
	{ type = "Muscle", model = "ruiner", label = "Ruiner" },
	{ type = "Muscle", model = "sabregt", label = "Sabre GT" },
	{ type = "Muscle", model = "sabregt2", label = "Sabre GT2" },
	{ type = "Muscle", model = "slamvan", label = "Slamvan" },
	{ type = "Muscle", model = "slamvan2", label = "Slamvan 2" },
	{ type = "Muscle", model = "slamvan3", label = "Slamvan 3" },
	{ type = "Muscle", model = "stalion", label = "Stalion" },
	{ type = "Muscle", model = "stalion2", label = "Stalion 2" },
	{ type = "Muscle", model = "tampa", label = "Tampa" },
	{ type = "Muscle", model = "tulip", label = "Tulip" },
	{ type = "Muscle", model = "vamos", label = "Vamos" },
	{ type = "Muscle", model = "vigero", label = "Vigero" },
	{ type = "Muscle", model = "virgo", label = "Virgo" },
	{ type = "Muscle", model = "virgo2", label = "Virgo 2" },
	{ type = "Muscle", model = "virgo3", label = "Virgo 3" },
	{ type = "Muscle", model = "voodoo", label = "Voodoo" },
	{ type = "Muscle", model = "voodoo2", label = "Voodoo 2" },
	{ type = "Muscle", model = "yosemite", label = "Yosemite" },
	{ type = "Muscle", model = "yosemite2", label = "Yosemite 2" },
	{ type = "Muscle", model = "yosemite3", label = "Yosemite 3" },
	{ type = "Off-Road", model = "bfinjection", label = "BF Injection" },
	{ type = "Off-Road", model = "bifta", label = "Bifta" },
	{ type = "Off-Road", model = "bodhi2", label = "Bodhi 2" },
	{ type = "Off-Road", model = "brawler", label = "Brawler" },
	{ type = "Off-Road", model = "brutus", label = "Brutus" },
	{ type = "Off-Road", model = "caracara2", label = "Caracara 2" },
	{ type = "Off-Road", model = "dloader", label = "DLoader" },
	{ type = "Off-Road", model = "dubsta3", label = "Dubsta 3" },
	{ type = "Off-Road", model = "dune", label = "Dune" },
	{ type = "Off-Road", model = "dune2", label = "Dune 2" },
	{ type = "Off-Road", model = "dune3", label = "Dune 3" },
	{ type = "Off-Road", model = "dune4", label = "Dune 4" },
	{ type = "Off-Road", model = "dune5", label = "Dune 5" },
	{ type = "Off-Road", model = "insurgent", label = "Insurgent" },
	{ type = "Off-Road", model = "insurgent2", label = "Insurgent 2" },
	{ type = "Off-Road", model = "insurgent3", label = "Insurgent 3" },
	{ type = "Off-Road", model = "everon", label = "Everon" },
	{ type = "Off-Road", model = "freecrawler", label = "Free Crawler" },
	{ type = "Off-Road", model = "hellion", label = "Hellion" },
	{ type = "Off-Road", model = "kalahari", label = "Kalahari" },
	{ type = "Off-Road", model = "kamacho", label = "Kamacho" },
	{ type = "Off-Road", model = "marshall", label = "Marshall" },
	{ type = "Off-Road", model = "mesa3", label = "Mesa 3" },
	{ type = "Off-Road", model = "monster", label = "Monster" },
	{ type = "Off-Road", model = "monster3", label = "Monster 3" },
	{ type = "Off-Road", model = "outlaw", label = "Outlaw" },
	{ type = "Off-Road", model = "rancherxl", label = "Rancher XL" },
	{ type = "Off-Road", model = "rancherxl2", label = "Rancher XL2" },
	{ type = "Off-Road", model = "rebel", label = "Rebel" },
	{ type = "Off-Road", model = "rebel2", label = "Rebel 2" },
	{ type = "Off-Road", model = "riata", label = "Riata" },
	{ type = "Off-Road", model = "sandking", label = "Sandking" },
	{ type = "Off-Road", model = "sandking2", label = "Sandking 2" },
	{ type = "Off-Road", model = "trophytruck", label = "Trophy Truck" },
	{ type = "Off-Road", model = "trophytruck2", label = "Trophy Truck 2" },
	{ type = "Off-Road", model = "technical", label = "Technical" },
	{ type = "Off-Road", model = "technical2", label = "Technical 2" },
	{ type = "Off-Road", model = "technical3", label = "Technical 3" },
	{ type = "Off-Road", model = "vagrant", label = "Vagrant" },
	{ type = "SUV's", model = "baller", label = "Baller" },
	{ type = "SUV's", model = "baller2", label = "Baller 2" },
	{ type = "SUV's", model = "baller3", label = "Baller 3" },
	{ type = "SUV's", model = "baller4", label = "Baller 4" },
	{ type = "SUV's", model = "bjxl", label = "BJXL" },
	{ type = "SUV's", model = "cavalcade", label = "Cavalcade" },
	{ type = "SUV's", model = "cavalcade2", label = "Cavalcade 2" },
	{ type = "SUV's", model = "contender", label = "Contender" },
	{ type = "SUV's", model = "dubsta", label = "Dubsta" },
	{ type = "SUV's", model = "dubsta2", label = "Dubsta 2" },
	{ type = "SUV's", model = "fq2", label = "FQ 2" },
	{ type = "SUV's", model = "granger", label = "Granger" },
	{ type = "SUV's", model = "gresley", label = "Gresley" },
	{ type = "SUV's", model = "habanero", label = "Habanero" },
	{ type = "SUV's", model = "huntley", label = "Huntley" },
	{ type = "SUV's", model = "landstalker", label = "Land Stalker" },
	{ type = "SUV's", model = "landstalker2", label = "Land Stalker 2" },
	{ type = "SUV's", model = "mesa", label = "Mesa" },
	{ type = "SUV's", model = "mesa2", label = "Mesa 2" },
	{ type = "SUV's", model = "novak", label = "Novak" },
	{ type = "SUV's", model = "patriot", label = "Patriot" },
	{ type = "SUV's", model = "patriot2", label = "Patriot 2" },
	{ type = "SUV's", model = "radi", label = "Radi" },
	{ type = "SUV's", model = "rebla", label = "Rebla" },
	{ type = "SUV's", model = "rocoto", label = "Rocoto" },
	{ type = "SUV's", model = "seminole", label = "Seminole" },
	{ type = "SUV's", model = "seminole2", label = "Seminole 2" },
	{ type = "SUV's", model = "serrano", label = "Serrano" },
	{ type = "SUV's", model = "toros", label = "Toros" },
	{ type = "SUV's", model = "xls", label = "XLS" },
	{ type = "Vans", model = "bison", label = "Bison" },
	{ type = "Vans", model = "bison2", label = "Bison 2" },
	{ type = "Vans", model = "bison3", label = "Bison 3" },
	{ type = "Vans", model = "bobcatxl", label = "Bobcat XL" },
	{ type = "Vans", model = "boxville", label = "Boxville" },
	{ type = "Vans", model = "boxville2", label = "Boxville 2" },
	{ type = "Vans", model = "boxville3", label = "Boxville 3" },
	{ type = "Vans", model = "boxville4", label = "Boxville 4" },
	{ type = "Vans", model = "burrito", label = "Burrito" },
	{ type = "Vans", model = "burrito2", label = "Burrito 2" },
	{ type = "Vans", model = "burrito3", label = "Burrito 3" },
	{ type = "Vans", model = "burrito4", label = "Burrito 4" },
	{ type = "Vans", model = "burrito5", label = "Burrito 5" },
	{ type = "Vans", model = "camper", label = "Camper" },
	{ type = "Vans", model = "gburrito", label = "Gang Burrito" },
	{ type = "Vans", model = "gburrito2", label = "Gang Burrito 2" },
	{ type = "Vans", model = "journey", label = "Journey" },
	{ type = "Vans", model = "minivan", label = "Minivan" },
	{ type = "Vans", model = "minivan2", label = "Minivan2" },
	{ type = "Vans", model = "paradise", label = "Paradise" },
	{ type = "Vans", model = "pony", label = "Pony" },
	{ type = "Vans", model = "pony2", label = "Pony 2" },
	{ type = "Vans", model = "rumpo", label = "Rumpo" },
	{ type = "Vans", model = "rumpo2", label = "Rumpo 2" },
	{ type = "Vans", model = "rumpo3", label = "Rumpo 3" },
	{ type = "Vans", model = "speedo", label = "Speedo" },
	{ type = "Vans", model = "speedo2", label = "Speedo 2" },
	{ type = "Vans", model = "speedo4", label = "Speedo 4" },
	{ type = "Vans", model = "surfer", label = "Surfer" },
	{ type = "Vans", model = "surfer2", label = "Surfer 2" },
	{ type = "Vans", model = "youga", label = "Youga" },
	{ type = "Vans", model = "youga2", label = "Youga 2" },
	{ type = "Vans", model = "youga3", label = "Youga 3" },
	{ type = "Cycles", model = "Bmx", label = "Bmx" },
	{ type = "Cycles", model = "Cruiser", label = "Cruiser" },
	{ type = "Cycles", model = "Fixter", label = "Fixter" },
	{ type = "Cycles", model = "Scorcher", label = "Scorcher" },
	{ type = "Cycles", model = "TriBike", label = "TriBike" },
	{ type = "Cycles", model = "TriBike2", label = "TriBike 2" },
	{ type = "Cycles", model = "TriBike3", label = "TriBike 3" },
	{ type = "Motorcycles", model = "akuma", label = "Akuma" },
	{ type = "Motorcycles", model = "avarus", label = "Avarus" },
	{ type = "Motorcycles", model = "bagger", label = "Bagger" },
	{ type = "Motorcycles", model = "bati", label = "Bati" },
	{ type = "Motorcycles", model = "bati2", label = "Bati 2" },
	{ type = "Motorcycles", model = "bf400", label = "BF 400" },
	{ type = "Motorcycles", model = "carbonrs", label = "Carbon RS" },
	{ type = "Motorcycles", model = "chimera", label = "Chimera" },
	{ type = "Motorcycles", model = "cliffhanger", label = "Cliff Hanger" },
	{ type = "Motorcycles", model = "daemon", label = "Daemon" },
	{ type = "Motorcycles", model = "daemon2", label = "Daemon 2" },
	{ type = "Motorcycles", model = "defiler", label = "Defiler" },
	{ type = "Motorcycles", model = "deathbike", label = "Death Bike" },
	{ type = "Motorcycles", model = "deathbike2", label = "Death Bike 2" },
	{ type = "Motorcycles", model = "deathbike3", label = "Death Bike 3" },
	{ type = "Motorcycles", model = "diablous", label = "Diablous" },
	{ type = "Motorcycles", model = "diablous2", label = "Diablous 2" },
	{ type = "Motorcycles", model = "double", label = "Double" },
	{ type = "Motorcycles", model = "enduro", label = "Enduro" },
	{ type = "Motorcycles", model = "esskey", label = "Esskey" },
	{ type = "Motorcycles", model = "faggio", label = "Faggio" },
	{ type = "Motorcycles", model = "faggio2", label = "Faggio 2" },
	{ type = "Motorcycles", model = "faggio3", label = "Faggio 3" },
	{ type = "Motorcycles", model = "fcr", label = "FCR" },
	{ type = "Motorcycles", model = "fcr2", label = "FCR 2" },
	{ type = "Motorcycles", model = "gargoyle", label = "Gargoyle" },
	{ type = "Motorcycles", model = "hakuchou", label = "Hakuchou" },
	{ type = "Motorcycles", model = "hakuchou2", label = "Hakuchou 2" },
	{ type = "Motorcycles", model = "hexer", label = "Hexer" },
	{ type = "Motorcycles", model = "innovation", label = "Innovation" },
	{ type = "Motorcycles", model = "lectro", label = "Lectro" },
	{ type = "Motorcycles", model = "manchez", label = "Manchez" },
	{ type = "Motorcycles", model = "manchez2", label = "Manchez 2" },
	{ type = "Motorcycles", model = "nemesis", label = "Nemesis" },
	{ type = "Motorcycles", model = "nightblade", label = "nightblade" },
	{ type = "Motorcycles", model = "pcj", label = "PCJ" },
	{ type = "Motorcycles", model = "ratbike", label = "Rat Bike" },
	{ type = "Motorcycles", model = "ruffian", label = "Ruffian" },
	{ type = "Motorcycles", model = "rrocket", label = "R Rocket" },
	{ type = "Motorcycles", model = "sanchez", label = "Sanchez" },
	{ type = "Motorcycles", model = "sanchez2", label = "Sanchez 2" },
	{ type = "Motorcycles", model = "sanctus", label = "Sanctus" },
	{ type = "Motorcycles", model = "sovereign", label = "Sovereign" },
	{ type = "Motorcycles", model = "stryder", label = "Stryder" },
	{ type = "Motorcycles", model = "thrust", label = "Thrust" },
	{ type = "Motorcycles", model = "vader", label = "Vader" },
	{ type = "Motorcycles", model = "vindicator", label = "Vindicator" },
	{ type = "Motorcycles", model = "vortex", label = "Vortex" },
	{ type = "Motorcycles", model = "wolfsbane", label = "Wolfsbane" },
	{ type = "Motorcycles", model = "zombiea", label = "Zombie A" },
	{ type = "Motorcycles", model = "zombieb", label = "Zombie B" },
}
