-- Variables initialization
-- init some local variables
_var = {
	client = {},
	menu = {},
	menus = {},
	activeThreads = {},
	vehicle = {},
	players = {},
	reports = {},
	instructionnal = {},
	noclip = {},
	peds = {},
}
_var.client.isStaffModeActivated = false
_var.client.staffGroup = nil
_var.client.playerData = {}
_var.client.userData = {}
_var.reports.list = {}
_var.players.list = {}
_var.players.selected = {}
_var.instructionnal.buttons = nil
_var.noclip.entity = false
_var.noclip.speedArrayIndex = 1
_var.noclip.speedArray = { 0, 0.5, 2, 5, 10, 15 }
_var.noclip.currentSpeed = _var.noclip.speedArray[_var.noclip.speedArrayIndex]
_var.noclip.speedLabel = ""
_var.noclip.offsets = { y = 0.5, z = 0.2, h = 20 }
_var.reports.count = 0
_var.reports.countHiden = 0
_var.reports.selectedReport = 1
_var.menus.admin = {
	isOpened = false,
	bannerTexture = nil,
	cooldowns = {
		items = false,
	},
	objects = {
		main = nil,
		mainPersonnal = nil,
		mainPersonnalAppearance = nil,
		mainPlayers = nil,
		mainPlayersInteract = nil,
		mainVehicles = nil,
		mainVehiclesCurrent = nil,
		mainVehiclesCurrentCustom = nil,
		mainVehiclesFavorites = nil,
		mainVehiclesSpawn = nil,
		mainReports = nil,
		mainReportsEdit = nil,
		mainReportsEditAdvanced = nil,
		mainServer = nil,
	},
}
_var.menu.cooldownStatus = false
_var.menu.isOpened = false
_var.menu.bannerTexture = nil
_var.menu.accountsActionsArrayIndex = 1
_var.menu.accountsActionsArray = {
	_("main_players_interact_money_action_add"),
	_("main_players_interact_money_action_remove"),
	_("main_players_interact_money_action_set"),
}
_var.menu.liveryArrayIndex = 1
_var.menu.modArrayIndex = 1
_var.menu.modVariantArrayIndex = 1
_var.menu.blackoutCheckbox = false
_var.menu.timeArrayIndex = 1
_var.menu.timeArray = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23 }
_var.menu.weatherArrayIndex = 1
_var.menu.weatherArray = {
	"EXTRASUNNY",
	"CLEAR",
	"SMOG",
	"FOGGY",
	"OVERCAST",
	"CLOUDS",
	"NEUTRAL",
	"CLEARING",
	"RAIN",
	"THUNDER",
	"SNOW",
	"SNOWLIGHT",
	"BLIZZARD",
	"XMAS",
	"HALLOWEEN",
}
_var.menu.pedsCategoryFilterArrayIndex = 1
_var.menu.pedsCategoryFilterArray = {
	_U("main_personnal_appearance_pedscategory0"),
	_U("main_personnal_appearance_pedscategory1"),
	_U("main_personnal_appearance_pedscategory2"),
	_U("main_personnal_appearance_pedscategory3"),
	_U("main_personnal_appearance_pedscategory4"),
	_U("main_personnal_appearance_pedscategory5"),
	_U("main_personnal_appearance_pedscategory6"),
	_U("main_personnal_appearance_pedscategory7"),
	_U("main_personnal_appearance_pedscategory8"),
	_U("main_personnal_appearance_pedscategory9"),
	_U("main_personnal_appearance_pedscategory10"),
	_U("main_personnal_appearance_pedscategory11"),
	_U("main_personnal_appearance_pedscategory12"),
}
_var.menu.reportsFilterArrayIndex = 1
_var.menu.reportsFilterArray = {
	_("main_reports_filter_all"),
	_("main_reports_filter_waiting"),
	_("main_reports_filter_taken"),
	_("main_reports_filter_taken_me"),
}
_var.menu.favritesActionsArrayIndex = 1
_var.menu.favritesActionsArray = {
	_("main_vehicles_favorites_interact_spawn"),
	_("main_vehicles_favorites_interact_delete"),
}
_var.menu.searchVehicle = ""
_var.menu.findedVehicle = nil
_var.activeThreads.getVehiclesFavorites = false
_var.activeThreads.getReports = false
_var.vehicle.doorArrayIndex = 1
_var.vehicle.doorArray = {
	_("door_frontleft"),
	_("door_frontright"),
	_("door_backleft"),
	_("door_backright"),
	_("door_hood"),
	_("door_trunk"),
	_("door_all"),
}
_var.keys = {
	["ESC"] = 322,
	["F1"] = 288,
	["F2"] = 289,
	["F3"] = 170,
	["F5"] = 166,
	["F6"] = 167,
	["F7"] = 168,
	["F8"] = 169,
	["F9"] = 56,
	["F10"] = 57,
	["~"] = 243,
	["1"] = 157,
	["2"] = 158,
	["3"] = 160,
	["4"] = 164,
	["5"] = 165,
	["6"] = 159,
	["7"] = 161,
	["8"] = 162,
	["9"] = 163,
	["-"] = 84,
	["="] = 83,
	["BACKSPACE"] = 177,
	["TAB"] = 37,
	["Q"] = 34,
	["W"] = 20,
	["E"] = 38,
	["R"] = 45,
	["T"] = 245,
	["Y"] = 246,
	["U"] = 303,
	["P"] = 199,
	["["] = 39,
	["]"] = 40,
	["ENTER"] = 18,
	["CAPS"] = 137,
	["A"] = 85,
	["S"] = 33,
	["D"] = 35,
	["F"] = 23,
	["G"] = 47,
	["H"] = 74,
	["K"] = 311,
	["L"] = 182,
	["LEFTSHIFT"] = 21,
	["Z"] = 32,
	["X"] = 73,
	["C"] = 26,
	["V"] = 0,
	["B"] = 29,
	["N"] = 249,
	["M"] = 244,
	[","] = 82,
	["."] = 81,
	["LEFTCTRL"] = 36,
	["LEFTALT"] = 19,
	["SPACE"] = 22,
	["RIGHTCTRL"] = 70,
	["HOME"] = 213,
	["PAGEUP"] = 10,
	["PAGEDOWN"] = 11,
	["DELETE"] = 178,
	["LEFT"] = 174,
	["RIGHT"] = 175,
	["TOP"] = 27,
	["DOWN"] = 173,
	["NENTER"] = 201,
	["N4"] = 108,
	["N5"] = 60,
	["N6"] = 107,
	["N+"] = 96,
	["N-"] = 97,
	["N7"] = 117,
	["N8"] = 61,
	["N9"] = 118,
}
_var.vehicle.paintColorsArrayIndexMain = 1
_var.vehicle.paintColorsArrayIndexSecondary = 1
_var.vehicle.paintColors = {
	{ "Chrome", 120 },
	{ "Black", 0 },
	{ "Carbon Black", 147 },
	{ "Graphite", 1 },
	{ "Anhracite Black", 11 },
	{ "Black Steel", 2 },
	{ "Dark Steel", 3 },
	{ "Silver", 4 },
	{ "Bluish Silver", 5 },
	{ "Rolled Steel", 6 },
	{ "Shadow Silver", 7 },
	{ "Stone Silver", 8 },
	{ "Midnight Silver", 9 },
	{ "Cast Iron Silver", 10 },
	{ "Red", 27 },
	{ "Torino Red", 28 },
	{ "Formula Red", 29 },
	{ "Lava Red", 150 },
	{ "Blaze Red", 30 },
	{ "Grace Red", 31 },
	{ "Garnet Red", 32 },
	{ "Sunset Red", 33 },
	{ "Cabernet Red", 34 },
	{ "Wine Red", 143 },
	{ "Candy Red", 35 },
	{ "Hot Pink", 135 },
	{ "Pfsiter Pink", 137 },
	{ "Salmon Pink", 136 },
	{ "Sunrise Orange", 36 },
	{ "Orange", 38 },
	{ "Bright Orange", 138 },
	{ "Gold", 99 },
	{ "Bronze", 90 },
	{ "Yellow", 88 },
	{ "Race Yellow", 89 },
	{ "Dew Yellow", 91 },
	{ "Dark Green", 49 },
	{ "Racing Green", 50 },
	{ "Sea Green", 51 },
	{ "Olive Green", 52 },
	{ "Bright Green", 53 },
	{ "Gasoline Green", 54 },
	{ "Lime Green", 92 },
	{ "Midnight Blue", 141 },
	{ "Galaxy Blue", 61 },
	{ "Dark Blue", 62 },
	{ "Saxon Blue", 63 },
	{ "Blue", 64 },
	{ "Mariner Blue", 65 },
	{ "Harbor Blue", 66 },
	{ "Diamond Blue", 67 },
	{ "Surf Blue", 68 },
	{ "Nautical Blue", 69 },
	{ "Racing Blue", 73 },
	{ "Ultra Blue", 70 },
	{ "Light Blue", 74 },
	{ "Chocolate Brown", 96 },
	{ "Bison Brown", 101 },
	{ "Creeen Brown", 95 },
	{ "Feltzer Brown", 94 },
	{ "Maple Brown", 97 },
	{ "Beechwood Brown", 103 },
	{ "Sienna Brown", 104 },
	{ "Saddle Brown", 98 },
	{ "Moss Brown", 100 },
	{ "Woodbeech Brown", 102 },
	{ "Straw Brown", 99 },
	{ "Sandy Brown", 105 },
	{ "Bleached Brown", 106 },
	{ "Schafter Purple", 71 },
	{ "Spinnaker Purple", 72 },
	{ "Midnight Purple", 142 },
	{ "Bright Purple", 145 },
	{ "Cream", 107 },
	{ "Ice White", 111 },
	{ "Frost White", 112 },
	{ "Black", 12 },
	{ "Gray", 13 },
	{ "Light Gray", 14 },
	{ "Ice White", 131 },
	{ "Blue", 83 },
	{ "Dark Blue", 82 },
	{ "Midnight Blue", 84 },
	{ "Midnight Purple", 149 },
	{ "Schafter Purple", 148 },
	{ "Red", 39 },
	{ "Dark Red", 40 },
	{ "Orange", 41 },
	{ "Yellow", 42 },
	{ "Lime Green", 55 },
	{ "Green", 128 },
	{ "Forest Green", 151 },
	{ "Foliage Green", 155 },
	{ "Olive Darb", 152 },
	{ "Dark Earth", 153 },
	{ "Desert Tan", 154 },
}
_var.vehicle.mods = {
	[1] = "Spoiler",
	[2] = "Front bumper",
	[3] = "Rear bumper",
	[4] = "Side skirt",
	[5] = "Exhaust",
	[6] = "Frame",
	[7] = "Grille",
	[8] = "Hood",
	[9] = "Fender",
	[10] = "Right fender",
	[11] = "Roof",
	[12] = "Engine",
	[13] = "Brakes",
	[14] = "Transmission",
	[15] = "Horns",
	[16] = "Suspension",
	[17] = "Armor",
	[18] = "Turbo",
	[19] = "Xenon",
	[20] = "Front wheels",
	[21] = "Back wheels",
	[22] = "Plate holders",
	[23] = "Trim design",
	[24] = "Ornaments",
	[25] = "Dial design",
	[26] = "Steering wheel",
	[27] = "Shift lever",
	[28] = "Plaques",
	[29] = "Hydraulics",
	[30] = "Boost",
	[31] = "Window tint",
	[32] = "Plate",
}
_var.vehicle.paintColorsArray = {}
for _, color in pairs(_var.vehicle.paintColors) do
	table.insert(_var.vehicle.paintColorsArray, color[1])
end
_var.vehicle.boostArrayIndex = 1
_var.vehicle.boostArray = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 }
_var.vehicle.list = {
	{ type = "Service", model = "airbus", label = "Airbus" },
	{ type = "Service", model = "brickade", label = "Brickade" },
	{ type = "Service", model = "bus", label = "Bus" },
	{ type = "Service", model = "coach", label = "Coach" },
	{ type = "Service", model = "rallytruck", label = "Rally Truck" },
	{ type = "Service", model = "rentalBus", label = "Rental Bus" },
	{ type = "Service", model = "taxi", label = "Taxi" },
	{ type = "Service", model = "tourbus", label = "Tour Bus" },
	{ type = "Service", model = "trash", label = "Trash" },
	{ type = "Service", model = "trash2", label = "Trash 2" },
	{ type = "Planes", model = "besra", label = "Besra" },
	{ type = "Planes", model = "blimp", label = "Blimp" },
	{ type = "Planes", model = "blimp2", label = "Blimp 2" },
	{ type = "Planes", model = "cargoPlane", label = "Cargo Plane" },
	{ type = "Planes", model = "cuban800", label = "Cuban800" },
	{ type = "Planes", model = "dodo", label = "Dodo" },
	{ type = "Planes", model = "duster", label = "Duster" },
	{ type = "Planes", model = "hydra", label = "Hydra" },
	{ type = "Planes", model = "jet", label = "Jet" },
	{ type = "Planes", model = "lazer", label = "Lazer" },
	{ type = "Planes", model = "luxor", label = "Luxor" },
	{ type = "Planes", model = "luxor2", label = "Luxor 2" },
	{ type = "Planes", model = "mammatus", label = "Mammatus" },
	{ type = "Planes", model = "miljet", label = "Miljet" },
	{ type = "Planes", model = "nimbus", label = "Nimbus" },
	{ type = "Planes", model = "shamal", label = "Shamal" },
	{ type = "Planes", model = "stunt", label = "Stunt" },
	{ type = "Planes", model = "titan", label = "Titan" },
	{ type = "Planes", model = "velum", label = "Velum" },
	{ type = "Planes", model = "velum2", label = "Velum2" },
	{ type = "Planes", model = "vestra", label = "Vestra" },
	{ type = "Military", model = "apc", label = "APC" },
	{ type = "Military", model = "barracks", label = "Barracks" },
	{ type = "Military", model = "barracks2", label = "Barracks 2" },
	{ type = "Military", model = "barracks3", label = "Barracks 3" },
	{ type = "Military", model = "crusader", label = "Crusader" },
	{ type = "Military", model = "halftrack", label = "Half Track" },
	{ type = "Military", model = "rhino", label = "Rhino" },
	{ type = "Industrials", model = "bulldozer", label = "Bulldozer" },
	{ type = "Industrials", model = "cutter", label = "Cutter" },
	{ type = "Industrials", model = "dump", label = "Dump" },
	{ type = "Industrials", model = "flatbed", label = "Flatbed" },
	{ type = "Industrials", model = "guardian", label = "Guardian" },
	{ type = "Industrials", model = "handler", label = "Handler" },
	{ type = "Industrials", model = "mixer", label = "Mixer" },
	{ type = "Industrials", model = "mixer2", label = "Mixer2" },
	{ type = "Industrials", model = "rubble", label = "Rubble" },
	{ type = "Industrials", model = "tipTruck", label = "TipTruck" },
	{ type = "Industrials", model = "tipTruck2", label = "TipTruck2" },
	{ type = "Helicopters", model = "annihilator", label = "Annihilator" },
	{ type = "Helicopters", model = "buzzard", label = "Buzzard" },
	{ type = "Helicopters", model = "buzzard2", label = "Buzzard 2" },
	{ type = "Helicopters", model = "cargobob", label = "Cargobob" },
	{ type = "Helicopters", model = "cargobob2", label = "Cargobob 2" },
	{ type = "Helicopters", model = "cargobob3", label = "Cargobob 3" },
	{ type = "Helicopters", model = "cargobob4", label = "Cargobob 4" },
	{ type = "Helicopters", model = "frogger", label = "Frogger" },
	{ type = "Helicopters", model = "frogger2", label = "Frogger 2" },
	{ type = "Helicopters", model = "maverick", label = "Maverick" },
	{ type = "Helicopters", model = "savage", label = "Savage" },
	{ type = "Helicopters", model = "skylift", label = "Skylift" },
	{ type = "Helicopters", model = "supervolito", label = "Super Volito" },
	{ type = "Helicopters", model = "supervolito2", label = "Super Volito 2" },
	{ type = "Helicopters", model = "swift", label = "Swift" },
	{ type = "Helicopters", model = "swift2", label = "Swift 2" },
	{ type = "Helicopters", model = "valkyrie", label = "Valkyrie" },
	{ type = "Helicopters", model = "valkyrie2", label = "Valkyrie 2" },
	{ type = "Helicopters", model = "volatus", label = "Volatus 2" },
	{ type = "Emergency", model = "ambulance", label = "Ambulance" },
	{ type = "Emergency", model = "fbi", label = "FBI" },
	{ type = "Emergency", model = "fbi2", label = "FBI 2" },
	{ type = "Emergency", model = "firetruck", label = "Fire Truck" },
	{ type = "Emergency", model = "pbus", label = "Police Bus" },
	{ type = "Emergency", model = "police", label = "Police" },
	{ type = "Emergency", model = "police2", label = "Police 2" },
	{ type = "Emergency", model = "police3", label = "Police 3" },
	{ type = "Emergency", model = "police4", label = "Police 4" },
	{ type = "Emergency", model = "policeold1", label = "PoliceOld1" },
	{ type = "Emergency", model = "policeold2", label = "PoliceOld 2" },
	{ type = "Emergency", model = "policeT", label = "PoliceT" },
	{ type = "Emergency", model = "policeb", label = "Policeb" },
	{ type = "Emergency", model = "polmav", label = "Polmav" },
	{ type = "Emergency", model = "pranger", label = "Pranger" },
	{ type = "Emergency", model = "predator", label = "Predator" },
	{ type = "Emergency", model = "riot", label = "Riot" },
	{ type = "Emergency", model = "sheriff", label = "Sheriff" },
	{ type = "Emergency", model = "sheriff2", label = "Sheriff 2" },
	{ type = "Boats", model = "dinghy", label = "Dinghy" },
	{ type = "Boats", model = "dinghy2", label = "Dinghy 2" },
	{ type = "Boats", model = "dinghy3", label = "Dinghy 3" },
	{ type = "Boats", model = "dinghy4", label = "Dinghy 4" },
	{ type = "Boats", model = "jetmax", label = "Jet Max" },
	{ type = "Boats", model = "marquis", label = "Marquis" },
	{ type = "Boats", model = "seashark", label = "Seashark" },
	{ type = "Boats", model = "seashark2", label = "Seashark 2" },
	{ type = "Boats", model = "seashark3", label = "Seashark 3" },
	{ type = "Boats", model = "speeder", label = "Speeder" },
	{ type = "Boats", model = "speeder2", label = "Speeder 2" },
	{ type = "Boats", model = "squalo", label = "Squalo" },
	{ type = "Boats", model = "submersible", label = "Sub Mersible" },
	{ type = "Boats", model = "submersible2", label = "Sub Mersible 2" },
	{ type = "Boats", model = "suntrap", label = "Sun Trap" },
	{ type = "Boats", model = "toro", label = "Toro" },
	{ type = "Boats", model = "toro2", label = "Toro 2" },
	{ type = "Boats", model = "tropic", label = "Tropic" },
	{ type = "Boats", model = "tropic2", label = "Tropic 2" },
	{ type = "Boats", model = "tug", label = "Tug" },
	{ type = "Commercials", model = "Benson", label = "Benson" },
	{ type = "Commercials", model = "Biff", label = "Biff" },
	{ type = "Commercials", model = "Hauler", label = "Hauler" },
	{ type = "Commercials", model = "Hauler2", label = "Hauler 2" },
	{ type = "Commercials", model = "Mule", label = "Mule" },
	{ type = "Commercials", model = "Mule2", label = "Mule 2" },
	{ type = "Commercials", model = "Mule3", label = "Mule 3" },
	{ type = "Commercials", model = "Packer", label = "Packer" },
	{ type = "Commercials", model = "Phantom", label = "Phantom" },
	{ type = "Commercials", model = "Phantom2", label = "Phantom 2" },
	{ type = "Commercials", model = "Phantom3", label = "Phantom 3" },
	{ type = "Commercials", model = "Pounder", label = "Pounder" },
	{ type = "Commercials", model = "Stockade", label = "Stockade" },
	{ type = "Commercials", model = "Stockade3", label = "Stockade 3" },
	{ type = "Compacts", model = "asbo", label = "Asbo" },
	{ type = "Compacts", model = "blista", label = "Blista" },
	{ type = "Compacts", model = "brioso", label = "Brioso" },
	{ type = "Compacts", model = "brioso2", label = "Brioso 2" },
	{ type = "Compacts", model = "club", label = "Club" },
	{ type = "Compacts", model = "dilettante", label = "Dilettante" },
	{ type = "Compacts", model = "dilettante2", label = "Dilettante2" },
	{ type = "Compacts", model = "issi2", label = "Issi 2" },
	{ type = "Compacts", model = "issi3", label = "Issi 3" },
	{ type = "Compacts", model = "issi5", label = "Issi 5" },
	{ type = "Compacts", model = "kanjo", label = "Kanjo" },
	{ type = "Compacts", model = "panto", label = "Panto" },
	{ type = "Compacts", model = "prairie", label = "Prairie" },
	{ type = "Compacts", model = "rhapsody", label = "Rhapsody" },
	{ type = "Compacts", model = "weevil", label = "Weevil" },
	{ type = "Coupes", model = "cogcabrio", label = "Cognoscenti Cabrio" },
	{ type = "Coupes", model = "exemplar", label = "Exemplar" },
	{ type = "Coupes", model = "f620", label = "F620" },
	{ type = "Coupes", model = "felon", label = "Felon" },
	{ type = "Coupes", model = "felon2", label = "Felon 2" },
	{ type = "Coupes", model = "jackal", label = "Jackal" },
	{ type = "Coupes", model = "oracle", label = "Oracle" },
	{ type = "Coupes", model = "oracle2", label = "Oracle 2" },
	{ type = "Coupes", model = "prairie", label = "Prairie" },
	{ type = "Coupes", model = "previon", label = "Previon" },
	{ type = "Coupes", model = "sentinel", label = "Sentinel" },
	{ type = "Coupes", model = "sentinel2", label = "Sentinel2" },
	{ type = "Coupes", model = "windsor", label = "Windsor" },
	{ type = "Coupes", model = "windsor2", label = "Windsor 2" },
	{ type = "Coupes", model = "zion", label = "Zion" },
	{ type = "Coupes", model = "zion2", label = "Zion 2" },
	{ type = "Sedans", model = "asea", label = "Asea" },
	{ type = "Sedans", model = "asea2", label = "Asea2" },
	{ type = "Sedans", model = "asterope", label = "Asterope" },
	{ type = "Sedans", model = "cog55", label = "Cognoscenti 55" },
	{ type = "Sedans", model = "cognoscenti", label = "Cognoscenti" },
	{ type = "Sedans", model = "emperor", label = "Emperor" },
	{ type = "Sedans", model = "emperor2", label = "Emperor 2" },
	{ type = "Sedans", model = "emperor3", label = "Emperor 3" },
	{ type = "Sedans", model = "fugitive", label = "Fugitive" },
	{ type = "Sedans", model = "glendale", label = "Glendale" },
	{ type = "Sedans", model = "glendale2", label = "Glendale 2" },
	{ type = "Sedans", model = "ingot", label = "Ingot" },
	{ type = "Sedans", model = "intruder", label = "Intruder" },
	{ type = "Sedans", model = "premier", label = "Premier" },
	{ type = "Sedans", model = "primo", label = "Primo" },
	{ type = "Sedans", model = "primo2", label = "Primo Custom" },
	{ type = "Sedans", model = "regina", label = "Regina" },
	{ type = "Sedans", model = "stafford", label = "Stafford" },
	{ type = "Sedans", model = "stanier", label = "Stanier" },
	{ type = "Sedans", model = "stratum", label = "Stratum" },
	{ type = "Sedans", model = "stretch", label = "Stretch" },
	{ type = "Sedans", model = "Superd", label = "Superd" },
	{ type = "Sedans", model = "surge", label = "Surge" },
	{ type = "Sedans", model = "tailgater", label = "Tailgater" },
	{ type = "Sedans", model = "tailgater2", label = "Tailgater2" },
	{ type = "Sedans", model = "warrener", label = "Warrener" },
	{ type = "Sedans", model = "washington", label = "Washington" },
	{ type = "Sports", model = "alpha", label = "Alpha" },
	{ type = "Sports", model = "banshee", label = "Banshee" },
	{ type = "Sports", model = "bestiagts", label = "Bestia GTS" },
	{ type = "Sports", model = "blista2", label = "Blista 2" },
	{ type = "Sports", model = "blista3", label = "Blista 3" },
	{ type = "Sports", model = "buffalo", label = "Buffalo" },
	{ type = "Sports", model = "buffalo2", label = "Buffalo Customs" },
	{ type = "Sports", model = "buffalo3", label = "Buffalo Sport" },
	{ type = "Sports", model = "carbonizzare", label = "Carbonizzare" },
	{ type = "Sports", model = "comet2", label = "Comet 2" },
	{ type = "Sports", model = "comet3", label = "Comet 3" },
	{ type = "Sports", model = "comet4", label = "Comet 4" },
	{ type = "Sports", model = "comet5", label = "Comet 5" },
	{ type = "Sports", model = "comet6", label = "Comet 6" },
	{ type = "Sports", model = "coquette", label = "Coquette" },
	{ type = "Sports", model = "coquette4", label = "Coquette 4" },
	{ type = "Sports", model = "cypher", label = "Cypher" },
	{ type = "Sports", model = "calico", label = "Calico" },
	{ type = "Sports", model = "drafter", label = "Drafter" },
	{ type = "Sports", model = "deveste", label = "Deveste" },
	{ type = "Sports", model = "elegy", label = "Elegy Retro" },
	{ type = "Sports", model = "elegy2", label = "Elegy" },
	{ type = "Sports", model = "euros", label = "Euros" },
	{ type = "Sports", model = "feltzer2", label = "Feltzer 2" },
	{ type = "Sports", model = "flashgt", label = "Flash GT" },
	{ type = "Sports", model = "furoregt", label = "Furore GT" },
	{ type = "Sports", model = "fusilade", label = "Fusilade" },
	{ type = "Sports", model = "futo", label = "Futo" },
	{ type = "Sports", model = "futo2", label = "Futo 2" },
	{ type = "Sports", model = "gb200", label = "GB200" },
	{ type = "Sports", model = "growler", label = "Growler" },
	{ type = "Sports", model = "hotring", label = "Hotring" },
	{ type = "Sports", model = "komoda", label = "Komoda" },
	{ type = "Sports", model = "imorgon", label = "Imorgon" },
	{ type = "Sports", model = "issi7", label = "Issi 7" },
	{ type = "Sports", model = "italigto", label = "Itali GTO" },
	{ type = "Sports", model = "italirsx", label = "Itali RSX" },
	{ type = "Sports", model = "jugular", label = "Jugular" },
	{ type = "Sports", model = "jester", label = "Jester" },
	{ type = "Sports", model = "jester2", label = "Jester 2" },
	{ type = "Sports", model = "jester3", label = "Jester 3" },
	{ type = "Sports", model = "jester4", label = "Jester 4" },
	{ type = "Sports", model = "khamelion", label = "Khamelion" },
	{ type = "Sports", model = "kuruma", label = "Kuruma" },
	{ type = "Sports", model = "locust", label = "Locust" },
	{ type = "Sports", model = "lynx", label = "Lynx" },
	{ type = "Sports", model = "massacro", label = "Massacro" },
	{ type = "Sports", model = "massacro2", label = "Massacro 2" },
	{ type = "Sports", model = "neo", label = "Neo" },
	{ type = "Sports", model = "neon", label = "Neon" },
	{ type = "Sports", model = "ninef", label = "Ninef" },
	{ type = "Sports", model = "ninef2", label = "Ninef 2" },
	{ type = "Sports", model = "omnis", label = "Omnis" },
	{ type = "Sports", model = "paragon", label = "Paragon" },
	{ type = "Sports", model = "paragon2", label = "Paragon 2" },
	{ type = "Sports", model = "pariah", label = "Pariah" },
	{ type = "Sports", model = "penumbra", label = "Penumbra" },
	{ type = "Sports", model = "penumbra2", label = "Penumbra 2" },
	{ type = "Sports", model = "raiden", label = "Raiden" },
	{ type = "Sports", model = "rapidgt", label = "Rapid GT" },
	{ type = "Sports", model = "rapidgt2", label = "Rapid GT2" },
	{ type = "Sports", model = "raptor", label = "Raptor" },
	{ type = "Sports", model = "revolter", label = "Revolter" },
	{ type = "Sports", model = "ruston", label = "Ruston" },
	{ type = "Sports", model = "rt3000", label = "RT3000" },
	{ type = "Sports", model = "remus", label = "Remus" },
	{ type = "Sports", model = "schafter2", label = "Schafter 2" },
	{ type = "Sports", model = "schafter3", label = "Schafter 3" },
	{ type = "Sports", model = "schafter4", label = "Schafter 4" },
	{ type = "Sports", model = "schlagen", label = "Schlagen" },
	{ type = "Sports", model = "schwarzer", label = "Schwarzer" },
	{ type = "Sports", model = "sentinel3", label = "Sentine l3" },
	{ type = "Sports", model = "seven70", label = "Seven 70" },
	{ type = "Sports", model = "specter", label = "Specter" },
	{ type = "Sports", model = "specter2", label = "Specter 2" },
	{ type = "Sports", model = "streiter", label = "Streiter" },
	{ type = "Sports", model = "sugoi", label = "Sugoi" },
	{ type = "Sports", model = "sultan", label = "Sultan" },
	{ type = "Sports", model = "sultan2", label = "Sultan Classic" },
	{ type = "Sports", model = "sultan3", label = "Sultan 3" },
	{ type = "Sports", model = "surano", label = "Surano" },
	{ type = "Sports", model = "tampa2", label = "Tampa 2" },
	{ type = "Sports", model = "tropos", label = "Tropos" },
	{ type = "Sports", model = "verlierer2", label = "Verlierer 2" },
	{ type = "Sports", model = "vstr", label = "VSTR" },
	{ type = "Sports", model = "vectre", label = "Vectre" },
	{ type = "Sports", model = "zr350", label = "ZR350" },
	{ type = "Sports Classic", model = "ardent", label = "Ardent" },
	{ type = "Sports Classic", model = "btype", label = "Btype" },
	{ type = "Sports Classic", model = "btype2", label = "Btype 2" },
	{ type = "Sports Classic", model = "btype3", label = "Btype 3" },
	{ type = "Sports Classic", model = "casco", label = "Casco" },
	{ type = "Sports Classic", model = "cheetah2", label = "Cheetah 2" },
	{ type = "Sports Classic", model = "coquette2", label = "Coquette 2" },
	{ type = "Sports Classic", model = "cheburek", label = "Cheburek" },
	{ type = "Sports Classic", model = "dynasty", label = "Dynasty" },
	{ type = "Sports Classic", model = "fagaloa", label = "Fagaloa" },
	{ type = "Sports Classic", model = "feltzer3", label = "Feltzer 3" },
	{ type = "Sports Classic", model = "gt500", label = "GT500" },
	{ type = "Sports Classic", model = "infernus2", label = "Infernus 2" },
	{ type = "Sports Classic", model = "jb700", label = "JB700" },
	{ type = "Sports Classic", model = "jb7002", label = "JB700 2" },
	{ type = "Sports Classic", model = "mamba", label = "Mamba" },
	{ type = "Sports Classic", model = "manana", label = "Manana" },
	{ type = "Sports Classic", model = "manana2", label = "Manana 2" },
	{ type = "Sports Classic", model = "michelli", label = "Michelli" },
	{ type = "Sports Classic", model = "monroe", label = "Monroe" },
	{ type = "Sports Classic", model = "nebula", label = "Nebula" },
	{ type = "Sports Classic", model = "peyote", label = "Peyote" },
	{ type = "Sports Classic", model = "peyote3", label = "Peyote 3" },
	{ type = "Sports Classic", model = "pigalle", label = "Pigalle" },
	{ type = "Sports Classic", model = "rapidgt3", label = "Rapid GT3" },
	{ type = "Sports Classic", model = "retinue", label = "Retinue" },
	{ type = "Sports Classic", model = "retinue2", label = "Retinue 2" },
	{ type = "Sports Classic", model = "savestra", label = "Savestra" },
	{ type = "Sports Classic", model = "stinger", label = "Stinger" },
	{ type = "Sports Classic", model = "stingergt", label = "Stingergt" },
	{ type = "Sports Classic", model = "stromberg", label = "Stromberg" },
	{ type = "Sports Classic", model = "swinger", label = "Swinger" },
	{ type = "Sports Classic", model = "torero", label = "Torero" },
	{ type = "Sports Classic", model = "tornado", label = "Tornado" },
	{ type = "Sports Classic", model = "tornado2", label = "Tornado 2" },
	{ type = "Sports Classic", model = "tornado3", label = "Tornado 3" },
	{ type = "Sports Classic", model = "tornado4", label = "Tornado 4" },
	{ type = "Sports Classic", model = "tornado5", label = "Tornado 5" },
	{ type = "Sports Classic", model = "tornado6", label = "Tornado 6" },
	{ type = "Sports Classic", model = "toreador", label = "Toreador" },
	{ type = "Sports Classic", model = "turismo2", label = "Turismo 2" },
	{ type = "Sports Classic", model = "viseris", label = "Viseris" },
	{ type = "Sports Classic", model = "z190", label = "Z190" },
	{ type = "Sports Classic", model = "ztype", label = "Ztype" },
	{ type = "Sports Classic", model = "zion3", label = "Zion 3" },
	{ type = "Super", model = "adder", label = "Adder" },
	{ type = "Super", model = "autarch", label = "Autarch" },
	{ type = "Super", model = "banshee2", label = "Banshee 2" },
	{ type = "Super", model = "bullet", label = "Bullet" },
	{ type = "Super", model = "cheetah", label = "Cheetah" },
	{ type = "Super", model = "cyclone", label = "Cyclone" },
	{ type = "Super", model = "entity2", label = "Entity2" },
	{ type = "Super", model = "entityxf", label = "Entity XF" },
	{ type = "Super", model = "emerus", label = "Emerus" },
	{ type = "Super", model = "fmj", label = "FMJ" },
	{ type = "Super", model = "furia", label = "Furia" },
	{ type = "Super", model = "gp1", label = "GP 1" },
	{ type = "Super", model = "infernus", label = "Infernus" },
	{ type = "Super", model = "italigtb", label = "Itali GTB" },
	{ type = "Super", model = "italigtb2", label = "Itali GTB2" },
	{ type = "Super", model = "krieger", label = "Krieger" },
	{ type = "Super", model = "le7b", label = "LE7b" },
	{ type = "Super", model = "nero", label = "Nero" },
	{ type = "Super", model = "nero2", label = "Nero 2" },
	{ type = "Super", model = "osiris", label = "Osiris" },
	{ type = "Super", model = "penetrator", label = "Penetrator" },
	{ type = "Super", model = "pfister811", label = "Pfister 811" },
	{ type = "Super", model = "prototipo", label = "Prototipo" },
	{ type = "Super", model = "reaper", label = "Reaper" },
	{ type = "Super", model = "s80", label = "S80" },
	{ type = "Super", model = "sc1", label = "SC1" },
	{ type = "Super", model = "sheava", label = "Sheava" },
	{ type = "Super", model = "sultanrs", label = "Sultan RS" },
	{ type = "Super", model = "t20", label = "T20" },
	{ type = "Super", model = "taipan", label = "Taipan" },
	{ type = "Super", model = "tempesta", label = "Tempesta" },
	{ type = "Super", model = "tezeract", label = "Tezeract" },
	{ type = "Super", model = "thrax", label = "Thrax" },
	{ type = "Super", model = "tigon", label = "Tigon" },
	{ type = "Super", model = "turismor", label = "Turismo R" },
	{ type = "Super", model = "tyrant", label = "Tyrant" },
	{ type = "Super", model = "tyrus", label = "Tyrus" },
	{ type = "Super", model = "vacca", label = "Vacca" },
	{ type = "Super", model = "vagner", label = "Vagner" },
	{ type = "Super", model = "visione", label = "Visione" },
	{ type = "Super", model = "voltic", label = "Voltic" },
	{ type = "Super", model = "xa21", label = "XA21" },
	{ type = "Super", model = "zentorno", label = "Zentorno" },
	{ type = "Super", model = "zorrusso", label = "Zorrusso" },
	{ type = "Muscle", model = "blade", label = "Blade" },
	{ type = "Muscle", model = "buccaneer", label = "Buccaneer" },
	{ type = "Muscle", model = "buccaneer2", label = "Buccaneer 2" },
	{ type = "Muscle", model = "chino", label = "Chino" },
	{ type = "Muscle", model = "chino2", label = "Chino 2" },
	{ type = "Muscle", model = "clique", label = "Clique" },
	{ type = "Muscle", model = "coquette3", label = "Coquette 3" },
	{ type = "Muscle", model = "deviant", label = "Deviant" },
	{ type = "Muscle", model = "dominator", label = "Dominator" },
	{ type = "Muscle", model = "dominator2", label = "Dominator 2" },
	{ type = "Muscle", model = "dominator3", label = "Dominator 3" },
	{ type = "Muscle", model = "dukes", label = "Dukes" },
	{ type = "Muscle", model = "dukes3", label = "Dukes 3" },
	{ type = "Muscle", model = "dominator7", label = "Dominator 7" },
	{ type = "Muscle", model = "faction", label = "Faction" },
	{ type = "Muscle", model = "faction2", label = "Faction 2" },
	{ type = "Muscle", model = "faction3", label = "Faction 3" },
	{ type = "Muscle", model = "ellie", label = "Ellie" },
	{ type = "Muscle", model = "gauntlet", label = "Gauntlet" },
	{ type = "Muscle", model = "gauntlet2", label = "Gauntlet 2" },
	{ type = "Muscle", model = "gauntlet3", label = "Gauntlet 3" },
	{ type = "Muscle", model = "gauntlet4", label = "Gauntlet 4" },
	{ type = "Muscle", model = "gauntlet5", label = "Gauntlet 5" },
	{ type = "Muscle", model = "hermes", label = "Hermes" },
	{ type = "Muscle", model = "hotknife", label = "Hotknife" },
	{ type = "Muscle", model = "hustler", label = "Hustler" },
	{ type = "Muscle", model = "impaler", label = "Impaler" },
	{ type = "Muscle", model = "impaler2", label = "Impaler 2" },
	{ type = "Muscle", model = "impaler3", label = "Impaler 3" },
	{ type = "Muscle", model = "impaler4", label = "Impaler 4" },
	{ type = "Muscle", model = "imperator", label = "Imperator" },
	{ type = "Muscle", model = "imperator2", label = "Imperator 2" },
	{ type = "Muscle", model = "lurcher", label = "Lurcher" },
	{ type = "Muscle", model = "moonbeam", label = "Moonbeam" },
	{ type = "Muscle", model = "moonbeam2", label = "Moonbeam 2" },
	{ type = "Muscle", model = "nightshade", label = "Nightshade" },
	{ type = "Muscle", model = "peyote2", label = "Peyote 2" },
	{ type = "Muscle", model = "phoenix", label = "Phoenix" },
	{ type = "Muscle", model = "picador", label = "Picador" },
	{ type = "Muscle", model = "ratloader", label = "Rat Loader" },
	{ type = "Muscle", model = "ratloader2", label = "Rat Loader 2" },
	{ type = "Muscle", model = "ruiner", label = "Ruiner" },
	{ type = "Muscle", model = "sabregt", label = "Sabre GT" },
	{ type = "Muscle", model = "sabregt2", label = "Sabre GT2" },
	{ type = "Muscle", model = "slamvan", label = "Slamvan" },
	{ type = "Muscle", model = "slamvan2", label = "Slamvan 2" },
	{ type = "Muscle", model = "slamvan3", label = "Slamvan 3" },
	{ type = "Muscle", model = "stalion", label = "Stalion" },
	{ type = "Muscle", model = "stalion2", label = "Stalion 2" },
	{ type = "Muscle", model = "tampa", label = "Tampa" },
	{ type = "Muscle", model = "tulip", label = "Tulip" },
	{ type = "Muscle", model = "vamos", label = "Vamos" },
	{ type = "Muscle", model = "vigero", label = "Vigero" },
	{ type = "Muscle", model = "virgo", label = "Virgo" },
	{ type = "Muscle", model = "virgo2", label = "Virgo 2" },
	{ type = "Muscle", model = "virgo3", label = "Virgo 3" },
	{ type = "Muscle", model = "voodoo", label = "Voodoo" },
	{ type = "Muscle", model = "voodoo2", label = "Voodoo 2" },
	{ type = "Muscle", model = "yosemite", label = "Yosemite" },
	{ type = "Muscle", model = "yosemite2", label = "Yosemite 2" },
	{ type = "Muscle", model = "yosemite3", label = "Yosemite 3" },
	{ type = "Off-Road", model = "bfinjection", label = "BF Injection" },
	{ type = "Off-Road", model = "bifta", label = "Bifta" },
	{ type = "Off-Road", model = "bodhi2", label = "Bodhi 2" },
	{ type = "Off-Road", model = "brawler", label = "Brawler" },
	{ type = "Off-Road", model = "brutus", label = "Brutus" },
	{ type = "Off-Road", model = "caracara2", label = "Caracara 2" },
	{ type = "Off-Road", model = "dloader", label = "DLoader" },
	{ type = "Off-Road", model = "dubsta3", label = "Dubsta 3" },
	{ type = "Off-Road", model = "dune", label = "Dune" },
	{ type = "Off-Road", model = "dune2", label = "Dune 2" },
	{ type = "Off-Road", model = "dune3", label = "Dune 3" },
	{ type = "Off-Road", model = "dune4", label = "Dune 4" },
	{ type = "Off-Road", model = "dune5", label = "Dune 5" },
	{ type = "Off-Road", model = "insurgent", label = "Insurgent" },
	{ type = "Off-Road", model = "insurgent2", label = "Insurgent 2" },
	{ type = "Off-Road", model = "insurgent3", label = "Insurgent 3" },
	{ type = "Off-Road", model = "everon", label = "Everon" },
	{ type = "Off-Road", model = "freecrawler", label = "Free Crawler" },
	{ type = "Off-Road", model = "hellion", label = "Hellion" },
	{ type = "Off-Road", model = "kalahari", label = "Kalahari" },
	{ type = "Off-Road", model = "kamacho", label = "Kamacho" },
	{ type = "Off-Road", model = "marshall", label = "Marshall" },
	{ type = "Off-Road", model = "mesa3", label = "Mesa 3" },
	{ type = "Off-Road", model = "monster", label = "Monster" },
	{ type = "Off-Road", model = "monster3", label = "Monster 3" },
	{ type = "Off-Road", model = "outlaw", label = "Outlaw" },
	{ type = "Off-Road", model = "rancherxl", label = "Rancher XL" },
	{ type = "Off-Road", model = "rancherxl2", label = "Rancher XL2" },
	{ type = "Off-Road", model = "rebel", label = "Rebel" },
	{ type = "Off-Road", model = "rebel2", label = "Rebel 2" },
	{ type = "Off-Road", model = "riata", label = "Riata" },
	{ type = "Off-Road", model = "sandking", label = "Sandking" },
	{ type = "Off-Road", model = "sandking2", label = "Sandking 2" },
	{ type = "Off-Road", model = "trophytruck", label = "Trophy Truck" },
	{ type = "Off-Road", model = "trophytruck2", label = "Trophy Truck 2" },
	{ type = "Off-Road", model = "technical", label = "Technical" },
	{ type = "Off-Road", model = "technical2", label = "Technical 2" },
	{ type = "Off-Road", model = "technical3", label = "Technical 3" },
	{ type = "Off-Road", model = "vagrant", label = "Vagrant" },
	{ type = "SUV's", model = "baller", label = "Baller" },
	{ type = "SUV's", model = "baller2", label = "Baller 2" },
	{ type = "SUV's", model = "baller3", label = "Baller 3" },
	{ type = "SUV's", model = "baller4", label = "Baller 4" },
	{ type = "SUV's", model = "bjxl", label = "BJXL" },
	{ type = "SUV's", model = "cavalcade", label = "Cavalcade" },
	{ type = "SUV's", model = "cavalcade2", label = "Cavalcade 2" },
	{ type = "SUV's", model = "contender", label = "Contender" },
	{ type = "SUV's", model = "dubsta", label = "Dubsta" },
	{ type = "SUV's", model = "dubsta2", label = "Dubsta 2" },
	{ type = "SUV's", model = "fq2", label = "FQ 2" },
	{ type = "SUV's", model = "granger", label = "Granger" },
	{ type = "SUV's", model = "gresley", label = "Gresley" },
	{ type = "SUV's", model = "habanero", label = "Habanero" },
	{ type = "SUV's", model = "huntley", label = "Huntley" },
	{ type = "SUV's", model = "landstalker", label = "Land Stalker" },
	{ type = "SUV's", model = "landstalker2", label = "Land Stalker 2" },
	{ type = "SUV's", model = "mesa", label = "Mesa" },
	{ type = "SUV's", model = "mesa2", label = "Mesa 2" },
	{ type = "SUV's", model = "novak", label = "Novak" },
	{ type = "SUV's", model = "patriot", label = "Patriot" },
	{ type = "SUV's", model = "patriot2", label = "Patriot 2" },
	{ type = "SUV's", model = "radi", label = "Radi" },
	{ type = "SUV's", model = "rebla", label = "Rebla" },
	{ type = "SUV's", model = "rocoto", label = "Rocoto" },
	{ type = "SUV's", model = "seminole", label = "Seminole" },
	{ type = "SUV's", model = "seminole2", label = "Seminole 2" },
	{ type = "SUV's", model = "serrano", label = "Serrano" },
	{ type = "SUV's", model = "toros", label = "Toros" },
	{ type = "SUV's", model = "xls", label = "XLS" },
	{ type = "Vans", model = "bison", label = "Bison" },
	{ type = "Vans", model = "bison2", label = "Bison 2" },
	{ type = "Vans", model = "bison3", label = "Bison 3" },
	{ type = "Vans", model = "bobcatxl", label = "Bobcat XL" },
	{ type = "Vans", model = "boxville", label = "Boxville" },
	{ type = "Vans", model = "boxville2", label = "Boxville 2" },
	{ type = "Vans", model = "boxville3", label = "Boxville 3" },
	{ type = "Vans", model = "boxville4", label = "Boxville 4" },
	{ type = "Vans", model = "burrito", label = "Burrito" },
	{ type = "Vans", model = "burrito2", label = "Burrito 2" },
	{ type = "Vans", model = "burrito3", label = "Burrito 3" },
	{ type = "Vans", model = "burrito4", label = "Burrito 4" },
	{ type = "Vans", model = "burrito5", label = "Burrito 5" },
	{ type = "Vans", model = "camper", label = "Camper" },
	{ type = "Vans", model = "gburrito", label = "Gang Burrito" },
	{ type = "Vans", model = "gburrito2", label = "Gang Burrito 2" },
	{ type = "Vans", model = "journey", label = "Journey" },
	{ type = "Vans", model = "minivan", label = "Minivan" },
	{ type = "Vans", model = "minivan2", label = "Minivan2" },
	{ type = "Vans", model = "paradise", label = "Paradise" },
	{ type = "Vans", model = "pony", label = "Pony" },
	{ type = "Vans", model = "pony2", label = "Pony 2" },
	{ type = "Vans", model = "rumpo", label = "Rumpo" },
	{ type = "Vans", model = "rumpo2", label = "Rumpo 2" },
	{ type = "Vans", model = "rumpo3", label = "Rumpo 3" },
	{ type = "Vans", model = "speedo", label = "Speedo" },
	{ type = "Vans", model = "speedo2", label = "Speedo 2" },
	{ type = "Vans", model = "speedo4", label = "Speedo 4" },
	{ type = "Vans", model = "surfer", label = "Surfer" },
	{ type = "Vans", model = "surfer2", label = "Surfer 2" },
	{ type = "Vans", model = "youga", label = "Youga" },
	{ type = "Vans", model = "youga2", label = "Youga 2" },
	{ type = "Vans", model = "youga3", label = "Youga 3" },
	{ type = "Cycles", model = "Bmx", label = "Bmx" },
	{ type = "Cycles", model = "Cruiser", label = "Cruiser" },
	{ type = "Cycles", model = "Fixter", label = "Fixter" },
	{ type = "Cycles", model = "Scorcher", label = "Scorcher" },
	{ type = "Cycles", model = "TriBike", label = "TriBike" },
	{ type = "Cycles", model = "TriBike2", label = "TriBike 2" },
	{ type = "Cycles", model = "TriBike3", label = "TriBike 3" },
	{ type = "Motorcycles", model = "akuma", label = "Akuma" },
	{ type = "Motorcycles", model = "avarus", label = "Avarus" },
	{ type = "Motorcycles", model = "bagger", label = "Bagger" },
	{ type = "Motorcycles", model = "bati", label = "Bati" },
	{ type = "Motorcycles", model = "bati2", label = "Bati 2" },
	{ type = "Motorcycles", model = "bf400", label = "BF 400" },
	{ type = "Motorcycles", model = "carbonrs", label = "Carbon RS" },
	{ type = "Motorcycles", model = "chimera", label = "Chimera" },
	{ type = "Motorcycles", model = "cliffhanger", label = "Cliff Hanger" },
	{ type = "Motorcycles", model = "daemon", label = "Daemon" },
	{ type = "Motorcycles", model = "daemon2", label = "Daemon 2" },
	{ type = "Motorcycles", model = "defiler", label = "Defiler" },
	{ type = "Motorcycles", model = "deathbike", label = "Death Bike" },
	{ type = "Motorcycles", model = "deathbike2", label = "Death Bike 2" },
	{ type = "Motorcycles", model = "deathbike3", label = "Death Bike 3" },
	{ type = "Motorcycles", model = "diablous", label = "Diablous" },
	{ type = "Motorcycles", model = "diablous2", label = "Diablous 2" },
	{ type = "Motorcycles", model = "double", label = "Double" },
	{ type = "Motorcycles", model = "enduro", label = "Enduro" },
	{ type = "Motorcycles", model = "esskey", label = "Esskey" },
	{ type = "Motorcycles", model = "faggio", label = "Faggio" },
	{ type = "Motorcycles", model = "faggio2", label = "Faggio 2" },
	{ type = "Motorcycles", model = "faggio3", label = "Faggio 3" },
	{ type = "Motorcycles", model = "fcr", label = "FCR" },
	{ type = "Motorcycles", model = "fcr2", label = "FCR 2" },
	{ type = "Motorcycles", model = "gargoyle", label = "Gargoyle" },
	{ type = "Motorcycles", model = "hakuchou", label = "Hakuchou" },
	{ type = "Motorcycles", model = "hakuchou2", label = "Hakuchou 2" },
	{ type = "Motorcycles", model = "hexer", label = "Hexer" },
	{ type = "Motorcycles", model = "innovation", label = "Innovation" },
	{ type = "Motorcycles", model = "lectro", label = "Lectro" },
	{ type = "Motorcycles", model = "manchez", label = "Manchez" },
	{ type = "Motorcycles", model = "manchez2", label = "Manchez 2" },
	{ type = "Motorcycles", model = "nemesis", label = "Nemesis" },
	{ type = "Motorcycles", model = "nightblade", label = "nightblade" },
	{ type = "Motorcycles", model = "pcj", label = "PCJ" },
	{ type = "Motorcycles", model = "ratbike", label = "Rat Bike" },
	{ type = "Motorcycles", model = "ruffian", label = "Ruffian" },
	{ type = "Motorcycles", model = "rrocket", label = "R Rocket" },
	{ type = "Motorcycles", model = "sanchez", label = "Sanchez" },
	{ type = "Motorcycles", model = "sanchez2", label = "Sanchez 2" },
	{ type = "Motorcycles", model = "sanctus", label = "Sanctus" },
	{ type = "Motorcycles", model = "sovereign", label = "Sovereign" },
	{ type = "Motorcycles", model = "stryder", label = "Stryder" },
	{ type = "Motorcycles", model = "thrust", label = "Thrust" },
	{ type = "Motorcycles", model = "vader", label = "Vader" },
	{ type = "Motorcycles", model = "vindicator", label = "Vindicator" },
	{ type = "Motorcycles", model = "vortex", label = "Vortex" },
	{ type = "Motorcycles", model = "wolfsbane", label = "Wolfsbane" },
	{ type = "Motorcycles", model = "zombiea", label = "Zombie A" },
	{ type = "Motorcycles", model = "zombieb", label = "Zombie B" },
}
_var.peds.list = {
	[1] = {
		category = _U("main_personnal_appearance_pedscategory1"),
		models = {
			[1] = { model = "a_f_m_beach_01", label = "Beach 01" },
			[2] = { model = "a_f_m_bevhills_01", label = "Bevhills 01" },
			[3] = { model = "a_f_m_bevhills_02", label = "Bevhills 02" },
			[4] = { model = "a_f_m_bodybuild_01", label = "Bodybuild 01" },
			[5] = { model = "a_f_m_business_02", label = "Business 02" },
			[6] = { model = "a_f_m_downtown_01", label = "Downtown 01" },
			[7] = { model = "a_f_m_eastsa_01", label = "Eastsa 01" },
			[8] = { model = "a_f_m_eastsa_02", label = "Eastsa 02" },
			[9] = { model = "a_f_m_fatbla_01", label = "Fatbla 01" },
			[10] = { model = "a_f_m_fatcult_01", label = "Fatcult 01" },
			[11] = { model = "a_f_m_fatwhite_01", label = "Fatwhite 01" },
			[12] = { model = "a_f_m_ktown_01", label = "Ktown 01" },
			[13] = { model = "a_f_m_ktown_02", label = "Ktown 02" },
			[14] = { model = "a_f_m_prolhost_01", label = "Prolhost 01" },
			[15] = { model = "a_f_m_salton_01", label = "Salton 01" },
			[16] = { model = "a_f_m_skidrow_01", label = "Skidrow 01" },
			[17] = { model = "a_f_m_soucent_01", label = "Soucent 01" },
			[18] = { model = "a_f_m_soucent_02", label = "Soucent 02" },
			[19] = { model = "a_f_m_soucentmc_01", label = "Soucentmc 01" },
			[20] = { model = "a_f_m_tourist_01", label = "Tourist 01" },
			[21] = { model = "a_f_m_tramp_01", label = "Tramp 01" },
			[22] = { model = "a_f_m_trampbeac_01", label = "Trampbeac 01" },
			[23] = { model = "a_f_o_genstreet_01", label = "Genstreet 01" },
			[24] = { model = "a_f_o_indian_01", label = "Indian 01" },
			[25] = { model = "a_f_o_ktown_01", label = "Ktown 01" },
			[26] = { model = "a_f_o_salton_01", label = "Salton 01" },
			[27] = { model = "a_f_o_soucent_01", label = "Soucent 01" },
			[28] = { model = "a_f_o_soucent_02", label = "Soucent 02" },
			[29] = { model = "a_f_y_beach_01", label = "Beach 01" },
			[30] = { model = "a_f_y_bevhills_01", label = "Bevhills 01" },
			[31] = { model = "a_f_y_bevhills_02", label = "Bevhills 02" },
			[32] = { model = "a_f_y_bevhills_03", label = "Bevhills 03" },
			[33] = { model = "a_f_y_bevhills_04", label = "Bevhills 04" },
			[34] = { model = "a_f_y_business_01", label = "Business 01" },
			[35] = { model = "a_f_y_business_02", label = "Business 02" },
			[36] = { model = "a_f_y_business_03", label = "Business 03" },
			[37] = { model = "a_f_y_business_04", label = "Business 04" },
			[38] = { model = "a_f_y_clubcust_01", label = "Clubcust 01" },
			[39] = { model = "a_f_y_clubcust_02", label = "Clubcust 02" },
			[40] = { model = "a_f_y_clubcust_03", label = "Clubcust 03" },
			[41] = { model = "a_f_y_eastsa_01", label = "Eastsa 01" },
			[42] = { model = "a_f_y_eastsa_02", label = "Eastsa 02" },
			[43] = { model = "a_f_y_eastsa_03", label = "Eastsa 03" },
			[44] = { model = "a_f_y_epsilon_01", label = "Epsilon 01" },
			[45] = { model = "a_f_y_femaleagent", label = "Femaleagent" },
			[46] = { model = "a_f_y_fitness_01", label = "Fitness 01" },
			[47] = { model = "a_f_y_fitness_02", label = "Fitness 02" },
			[48] = { model = "a_f_y_genhot_01", label = "Genhot 01" },
			[49] = { model = "a_f_y_golfer_01", label = "Golfer 01" },
			[50] = { model = "a_f_y_hiker_01", label = "Hiker 01" },
			[51] = { model = "a_f_y_hippie_01", label = "Hippie 01" },
			[52] = { model = "a_f_y_hipster_01", label = "Hipster 01" },
			[53] = { model = "a_f_y_hipster_02", label = "Hipster 02" },
			[54] = { model = "a_f_y_hipster_03", label = "Hipster 03" },
			[55] = { model = "a_f_y_hipster_04", label = "Hipster 04" },
			[56] = { model = "a_f_y_indian_01", label = "Indian 01" },
			[57] = { model = "a_f_y_juggalo_01", label = "Juggalo 01" },
			[58] = { model = "a_f_y_runner_01", label = "Runner 01" },
			[59] = { model = "a_f_y_rurmeth_01", label = "Rurmeth 01" },
			[60] = { model = "a_f_y_scdressy_01", label = "Scdressy 01" },
			[61] = { model = "a_f_y_skater_01", label = "Skater 01" },
			[62] = { model = "a_f_y_soucent_01", label = "Soucent 01" },
			[63] = { model = "a_f_y_soucent_02", label = "Soucent 02" },
			[64] = { model = "a_f_y_soucent_03", label = "Soucent 03" },
			[65] = { model = "a_f_y_tennis_01", label = "Tennis 01" },
			[66] = { model = "a_f_y_topless_01", label = "Topless 01" },
			[67] = { model = "a_f_y_tourist_01", label = "Tourist 01" },
			[68] = { model = "a_f_y_tourist_02", label = "Tourist 02" },
			[69] = { model = "a_f_y_vinewood_01", label = "Vinewood 01" },
			[70] = { model = "a_f_y_vinewood_02", label = "Vinewood 02" },
			[71] = { model = "a_f_y_vinewood_03", label = "Vinewood 03" },
			[72] = { model = "a_f_y_vinewood_04", label = "Vinewood 04" },
			[73] = { model = "a_f_y_yoga_01", label = "Yoga 01" },
			[74] = { model = "a_f_y_gencaspat_01", label = "Gencaspat 01" },
			[75] = { model = "a_f_y_smartcaspat_01", label = "Smartcaspat 01" },
		},
	},
	[2] = {
		category = _U("main_personnal_appearance_pedscategory2"),
		models = {
			[1] = { model = "a_m_m_acult_01", label = "Acult 01" },
			[2] = { model = "a_m_m_afriamer_01", label = "Afriamer 01" },
			[3] = { model = "a_m_m_beach_01", label = "Beach 01" },
			[4] = { model = "a_m_m_beach_02", label = "Beach 02" },
			[5] = { model = "a_m_m_bevhills_01", label = "Bevhills 01" },
			[6] = { model = "a_m_m_bevhills_02", label = "Bevhills 02" },
			[7] = { model = "a_m_m_business_01", label = "Business 01" },
			[8] = { model = "a_m_m_eastsa_01", label = "Eastsa 01" },
			[9] = { model = "a_m_m_eastsa_02", label = "Eastsa 02" },
			[10] = { model = "a_m_m_farmer_01", label = "Farmer 01" },
			[11] = { model = "a_m_m_fatlatin_01", label = "Fatlatin 01" },
			[12] = { model = "a_m_m_genfat_01", label = "Genfat 01" },
			[13] = { model = "a_m_m_genfat_02", label = "Genfat 02" },
			[14] = { model = "a_m_m_golfer_01", label = "Golfer 01" },
			[15] = { model = "a_m_m_hasjew_01", label = "Hasjew 01" },
			[16] = { model = "a_m_m_hillbilly_01", label = "Hillbilly 01" },
			[17] = { model = "a_m_m_hillbilly_02", label = "Hillbilly 02" },
			[18] = { model = "a_m_m_indian_01", label = "Indian 01" },
			[19] = { model = "a_m_m_ktown_01", label = "Ktown 01" },
			[20] = { model = "a_m_m_malibu_01", label = "Malibu 01" },
			[21] = { model = "a_m_m_mexcntry_01", label = "Mexcntry 01" },
			[22] = { model = "a_m_m_mexlabor_01", label = "Mexlabor 01" },
			[23] = { model = "a_m_m_og_boss_01", label = "Og Boss 01" },
			[24] = { model = "a_m_m_paparazzi_01", label = "Paparazzi 01" },
			[25] = { model = "a_m_m_polynesian_01", label = "Polynesian 01" },
			[26] = { model = "a_m_m_prolhost_01", label = "Prolhost 01" },
			[27] = { model = "a_m_m_rurmeth_01", label = "Rurmeth 01" },
			[28] = { model = "a_m_m_salton_01", label = "Salton 01" },
			[29] = { model = "a_m_m_salton_02", label = "Salton 02" },
			[30] = { model = "a_m_m_salton_03", label = "Salton 03" },
			[31] = { model = "a_m_m_salton_04", label = "Salton 04" },
			[32] = { model = "a_m_m_skater_01", label = "Skater 01" },
			[33] = { model = "a_m_m_skidrow_01", label = "Skidrow 01" },
			[34] = { model = "a_m_m_socenlat_01", label = "Socenlat 01" },
			[35] = { model = "a_m_m_soucent_01", label = "Soucent 01" },
			[36] = { model = "a_m_m_soucent_02", label = "Soucent 02" },
			[37] = { model = "a_m_m_soucent_03", label = "Soucent 03" },
			[38] = { model = "a_m_m_soucent_04", label = "Soucent 04" },
			[39] = { model = "a_m_m_stlat_02", label = "Stlat 02" },
			[40] = { model = "a_m_m_tennis_01", label = "Tennis 01" },
			[41] = { model = "a_m_m_tourist_01", label = "Tourist 01" },
			[42] = { model = "a_m_m_tramp_01", label = "Tramp 01" },
			[43] = { model = "a_m_m_trampbeac_01", label = "Trampbeac 01" },
			[44] = { model = "a_m_m_tranvest_01", label = "Tranvest 01" },
			[45] = { model = "a_m_m_tranvest_02", label = "Tranvest 02" },
			[46] = { model = "a_m_o_acult_01", label = "Acult 01" },
			[47] = { model = "a_m_o_acult_02", label = "Acult 02" },
			[48] = { model = "a_m_o_beach_01", label = "Beach 01" },
			[49] = { model = "a_m_o_genstreet_01", label = "Genstreet 01" },
			[50] = { model = "a_m_o_ktown_01", label = "Ktown 01" },
			[51] = { model = "a_m_o_salton_01", label = "Salton 01" },
			[52] = { model = "a_m_o_soucent_01", label = "Soucent 01" },
			[53] = { model = "a_m_o_soucent_02", label = "Soucent 02" },
			[54] = { model = "a_m_o_soucent_03", label = "Soucent 03" },
			[55] = { model = "a_m_o_tramp_01", label = "Tramp 01" },
			[56] = { model = "a_m_y_acult_01", label = "Acult 01" },
			[57] = { model = "a_m_y_acult_02", label = "Acult 02" },
			[58] = { model = "a_m_y_beach_01", label = "Beach 01" },
			[59] = { model = "a_m_y_beach_02", label = "Beach 02" },
			[60] = { model = "a_m_y_beach_03", label = "Beach 03" },
			[61] = { model = "a_m_y_beachvesp_01", label = "Beachvesp 01" },
			[62] = { model = "a_m_y_beachvesp_02", label = "Beachvesp 02" },
			[63] = { model = "a_m_y_bevhills_01", label = "Bevhills 01" },
			[64] = { model = "a_m_y_bevhills_02", label = "Bevhills 02" },
			[65] = { model = "a_m_y_breakdance_01", label = "Breakdance 01" },
			[66] = { model = "a_m_y_busicas_01", label = "Busicas 01" },
			[67] = { model = "a_m_y_business_01", label = "Business 01" },
			[68] = { model = "a_m_y_business_02", label = "Business 02" },
			[69] = { model = "a_m_y_business_03", label = "Business 03" },
			[70] = { model = "a_m_y_clubcust_01", label = "Clubcust 01" },
			[71] = { model = "a_m_y_clubcust_02", label = "Clubcust 02" },
			[72] = { model = "a_m_y_clubcust_03", label = "Clubcust 03" },
			[73] = { model = "a_m_y_cyclist_01", label = "Cyclist 01" },
			[74] = { model = "a_m_y_dhill_01", label = "Dhill 01" },
			[75] = { model = "a_m_y_downtown_01", label = "Downtown 01" },
			[76] = { model = "a_m_y_eastsa_01", label = "Eastsa 01" },
			[77] = { model = "a_m_y_eastsa_02", label = "Eastsa 02" },
			[78] = { model = "a_m_y_epsilon_01", label = "Epsilon 01" },
			[79] = { model = "a_m_y_epsilon_02", label = "Epsilon 02" },
			[80] = { model = "a_m_y_gay_01", label = "Gay 01" },
			[81] = { model = "a_m_y_gay_02", label = "Gay 02" },
			[82] = { model = "a_m_y_genstreet_01", label = "Genstreet 01" },
			[83] = { model = "a_m_y_genstreet_02", label = "Genstreet 02" },
			[84] = { model = "a_m_y_golfer_01", label = "Golfer 01" },
			[85] = { model = "a_m_y_hasjew_01", label = "Hasjew 01" },
			[86] = { model = "a_m_y_hiker_01", label = "Hiker 01" },
			[87] = { model = "a_m_y_hippy_01", label = "Hippy 01" },
			[88] = { model = "a_m_y_hipster_01", label = "Hipster 01" },
			[89] = { model = "a_m_y_hipster_02", label = "Hipster 02" },
			[90] = { model = "a_m_y_hipster_03", label = "Hipster 03" },
			[91] = { model = "a_m_y_indian_01", label = "Indian 01" },
			[92] = { model = "a_m_y_jetski_01", label = "Jetski 01" },
			[93] = { model = "a_m_y_juggalo_01", label = "Juggalo 01" },
			[94] = { model = "a_m_y_ktown_01", label = "Ktown 01" },
			[95] = { model = "a_m_y_ktown_02", label = "Ktown 02" },
			[96] = { model = "a_m_y_latino_01", label = "Latino 01" },
			[97] = { model = "a_m_y_methhead_01", label = "Methhead 01" },
			[98] = { model = "a_m_y_mexthug_01", label = "Mexthug 01" },
			[99] = { model = "a_m_y_motox_01", label = "Motox 01" },
			[100] = { model = "a_m_y_motox_02", label = "Motox 02" },
			[101] = { model = "a_m_y_musclbeac_01", label = "Musclbeac 01" },
			[102] = { model = "a_m_y_musclbeac_02", label = "Musclbeac 02" },
			[103] = { model = "a_m_y_polynesian_01", label = "Polynesian 01" },
			[104] = { model = "a_m_y_roadcyc_01", label = "Roadcyc 01" },
			[105] = { model = "a_m_y_runner_01", label = "Runner 01" },
			[106] = { model = "a_m_y_runner_02", label = "Runner 02" },
			[107] = { model = "a_m_y_salton_01", label = "Salton 01" },
			[108] = { model = "a_m_y_skater_01", label = "Skater 01" },
			[109] = { model = "a_m_y_skater_02", label = "Skater 02" },
			[110] = { model = "a_m_y_soucent_01", label = "Soucent 01" },
			[111] = { model = "a_m_y_soucent_02", label = "Soucent 02" },
			[112] = { model = "a_m_y_soucent_03", label = "Soucent 03" },
			[113] = { model = "a_m_y_soucent_04", label = "Soucent 04" },
			[114] = { model = "a_m_y_stbla_01", label = "Stbla 01" },
			[115] = { model = "a_m_y_stbla_02", label = "Stbla 02" },
			[116] = { model = "a_m_y_stlat_01", label = "Stlat 01" },
			[117] = { model = "a_m_y_stwhi_01", label = "Stwhi 01" },
			[118] = { model = "a_m_y_stwhi_02", label = "Stwhi 02" },
			[119] = { model = "a_m_y_sunbathe_01", label = "Sunbathe 01" },
			[120] = { model = "a_m_y_surfer_01", label = "Surfer 01" },
			[121] = { model = "a_m_y_vindouche_01", label = "Vindouche 01" },
			[122] = { model = "a_m_y_vinewood_01", label = "Vinewood 01" },
			[123] = { model = "a_m_y_vinewood_02", label = "Vinewood 02" },
			[124] = { model = "a_m_y_vinewood_03", label = "Vinewood 03" },
			[125] = { model = "a_m_y_vinewood_04", label = "Vinewood 04" },
			[126] = { model = "a_m_y_yoga_01", label = "Yoga 01" },
			[127] = { model = "a_m_m_mlcrisis_01", label = "Mlcrisis 01" },
			[128] = { model = "a_m_y_gencaspat_01", label = "Gencaspat 01" },
			[129] = { model = "a_m_y_smartcaspat_01", label = "Smartcaspat 01" },
		},
	},
	[3] = {
		category = _U("main_personnal_appearance_pedscategory3"),
		models = {
			[1] = { model = "a_c_boar", label = "Boar" },
			[2] = { model = "a_c_cat_01", label = "Cat 01" },
			[3] = { model = "a_c_chickenhawk", label = "Chickenhawk" },
			[4] = { model = "a_c_chimp", label = "Chimp" },
			[5] = { model = "a_c_chop", label = "Chop" },
			[6] = { model = "a_c_cormorant", label = "Cormorant" },
			[7] = { model = "a_c_cow", label = "Cow" },
			[8] = { model = "a_c_coyote", label = "Coyote" },
			[9] = { model = "a_c_crow", label = "Crow" },
			[10] = { model = "a_c_deer", label = "Deer" },
			[11] = { model = "a_c_dolphin", label = "Dolphin" },
			[12] = { model = "a_c_fish", label = "Fish" },
			[13] = { model = "a_c_hen", label = "Hen" },
			[14] = { model = "a_c_humpback", label = "Humpback" },
			[15] = { model = "a_c_husky", label = "Husky" },
			[16] = { model = "a_c_killerwhale", label = "Killer Whale" },
			[17] = { model = "a_c_mtlion", label = "Mountain Lion" },
			[18] = { model = "a_c_pig", label = "Pig" },
			[19] = { model = "a_c_pigeon", label = "Pigeon" },
			[20] = { model = "a_c_poodle", label = "Poodle" },
			[21] = { model = "a_c_pug", label = "Pug" },
			[22] = { model = "a_c_rabbit_01", label = "Rabbit 01" },
			[23] = { model = "a_c_rat", label = "Rat" },
			[24] = { model = "a_c_retriever", label = "Retriever" },
			[25] = { model = "a_c_rhesus", label = "Rhesus" },
			[26] = { model = "a_c_rottweiler", label = "Rottweiler" },
			[27] = { model = "a_c_seagull", label = "Seagull" },
			[28] = { model = "a_c_sharkhammer", label = "Shark Hammer" },
			[29] = { model = "a_c_sharktiger", label = "Shark Tiger" },
			[30] = { model = "a_c_shepherd", label = "Shepherd" },
			[31] = { model = "a_c_stingray", label = "Stingray" },
			[32] = { model = "a_c_westy", label = "Westy" },
		},
	},
	[4] = {
		category = _U("main_personnal_appearance_pedscategory4"),
		models = {
			[1] = { model = "cs_amandatownley", label = "Amanda Townley" },
			[2] = { model = "cs_andreas", label = "Andreas" },
			[3] = { model = "cs_ashley", label = "Ashley" },
			[4] = { model = "cs_bankman", label = "Bankman" },
			[5] = { model = "cs_barry", label = "Barry" },
			[6] = { model = "cs_beverly", label = "Beverly" },
			[7] = { model = "cs_brad", label = "Brad" },
			[8] = { model = "cs_bradcadaver", label = "Brad Cadaver" },
			[9] = { model = "cs_carbuyer", label = "Car Buyer" },
			[10] = { model = "cs_casey", label = "Casey" },
			[11] = { model = "cs_chengsr", label = "Cheng Sr" },
			[12] = { model = "cs_chrisformage", label = "Chris Formage" },
			[13] = { model = "cs_clay", label = "Clay" },
			[14] = { model = "cs_dale", label = "Dale" },
			[15] = { model = "cs_davenorton", label = "Dave Norton" },
			[16] = { model = "cs_debra", label = "Debra" },
			[17] = { model = "cs_denise", label = "Denise" },
			[18] = { model = "cs_devin", label = "Devin" },
			[19] = { model = "cs_dom", label = "Dom" },
			[20] = { model = "cs_dreyfuss", label = "Dreyfuss" },
			[21] = { model = "cs_drfriedlander", label = "Dr. Friedlander" },
			[22] = { model = "cs_fabien", label = "Fabien" },
			[23] = { model = "cs_fbisuit_01", label = "FBI Suit 01" },
			[24] = { model = "cs_floyd", label = "Floyd" },
			[25] = { model = "cs_guadalope", label = "Guadalope" },
			[26] = { model = "cs_gurk", label = "Gurk" },
			[27] = { model = "cs_hunter", label = "Hunter" },
			[28] = { model = "cs_janet", label = "Janet" },
			[29] = { model = "cs_jewelass", label = "Jewelass" },
			[30] = { model = "cs_jimmyboston", label = "Jimmy Boston" },
			[31] = { model = "cs_jimmydisanto", label = "Jimmy Di Santa" },
			[32] = { model = "cs_joeminuteman", label = "Joe Minuteman" },
			[33] = { model = "cs_johnnyklebitz", label = "Johnny Klebitz" },
			[34] = { model = "cs_josef", label = "Josef" },
			[35] = { model = "cs_josh", label = "Josh" },
			[36] = { model = "cs_karen_daniels", label = "Karen Daniels" },
			[37] = { model = "cs_lamardavis", label = "Lamar Davis" },
			[38] = { model = "cs_lazlow", label = "Lazlow" },
			[39] = { model = "cs_lazlow_2", label = "Lazlow 2" },
			[40] = { model = "cs_lestercrest", label = "Lester Crest" },
			[41] = { model = "cs_lifeinvad_01", label = "Lifeinvad 01" },
			[42] = { model = "cs_magenta", label = "Magenta" },
			[43] = { model = "cs_manuel", label = "Manuel" },
			[44] = { model = "cs_marnie", label = "Marnie" },
			[45] = { model = "cs_martinmadrazo", label = "Martin Madrazo" },
			[46] = { model = "cs_maryann", label = "Mary-Ann" },
			[47] = { model = "cs_michelle", label = "Michelle" },
			[48] = { model = "cs_milton", label = "Milton" },
			[49] = { model = "cs_molly", label = "Molly" },
			[50] = { model = "cs_movpremf_01", label = "Movpremf 01" },
			[51] = { model = "cs_movpremmale", label = "Movpremmale" },
			[52] = { model = "cs_mrk", label = "Mr. K" },
			[53] = { model = "cs_mrs_thornhill", label = "Mrs. Thornhill" },
			[54] = { model = "cs_mrsphillips", label = "Mrs. Phillips" },
			[55] = { model = "cs_natalia", label = "Natalia" },
			[56] = { model = "cs_nervousron", label = "Nervous Ron" },
			[57] = { model = "cs_nigel", label = "Nigel" },
			[58] = { model = "cs_old_man1a", label = "Old Man 1a" },
			[59] = { model = "cs_old_man2", label = "Old Man 2" },
			[60] = { model = "cs_omega", label = "Omega" },
			[61] = { model = "cs_orleans", label = "Orleans" },
			[62] = { model = "cs_paper", label = "Paper" },
			[63] = { model = "cs_patricia", label = "Patricia" },
			[64] = { model = "cs_priest", label = "Priest" },
			[65] = { model = "cs_prolsec_02", label = "Prolsec 02" },
			[66] = { model = "cs_russiandrunk", label = "Russian Drunk" },
			[67] = { model = "cs_siemonyetarian", label = "Siemon Yetarian" },
			[68] = { model = "cs_solomon", label = "Solomon" },
			[69] = { model = "cs_stevehains", label = "Steve Hains" },
			[70] = { model = "cs_stretch", label = "Stretch" },
			[71] = { model = "cs_tanisha", label = "Tanisha" },
			[72] = { model = "cs_taocheng", label = "Tao Cheng" },
			[73] = { model = "cs_taostranslator", label = "Tao's Translator" },
			[74] = { model = "cs_tenniscoach", label = "Tennis Coach" },
			[75] = { model = "cs_terry", label = "Terry" },
			[76] = { model = "cs_tom", label = "Tom" },
			[77] = { model = "cs_tomepsilon", label = "Tom Epsilon" },
			[78] = { model = "cs_tracydisanto", label = "Tracy Di Santa" },
			[79] = { model = "cs_wade", label = "Wade" },
			[80] = { model = "cs_zimbor", label = "Zimbor" },
			[81] = { model = "csb_abigail", label = "Abigail" },
			[82] = { model = "csb_agent", label = "Agent" },
			[83] = { model = "csb_alan", label = "Alan" },
			[84] = { model = "csb_anita", label = "Anita" },
			[85] = { model = "csb_anton", label = "Anton" },
			[86] = { model = "csb_avon", label = "Avon" },
			[87] = { model = "csb_ballasog", label = "Ballas OG" },
			[88] = { model = "csb_bogdan", label = "Bogdan" },
			[89] = { model = "csb_bride", label = "Bride" },
			[90] = { model = "csb_bryony", label = "Bryony" },
			[91] = { model = "csb_burgerdrug", label = "Burger Drug" },
			[92] = { model = "csb_car3guy1", label = "Car 3 Guy 1" },
			[93] = { model = "csb_car3guy2", label = "Car 3 Guy 2" },
			[94] = { model = "csb_chef", label = "Chef" },
			[95] = { model = "csb_chef2", label = "Chef 2" },
			[96] = { model = "csb_chin_goon", label = "Chin Goon" },
			[97] = { model = "csb_cletus", label = "Cletus" },
			[98] = { model = "csb_cop", label = "Cop" },
			[99] = { model = "csb_customer", label = "Customer" },
			[100] = { model = "csb_denise_friend", label = "Denise Friend" },
			[101] = { model = "csb_dix", label = "Dix" },
			[102] = { model = "csb_djblamadon", label = "DJ Blamadon" },
			[103] = { model = "csb_englishdave", label = "English Dave" },
			[104] = { model = "csb_fos_rep", label = "FOS Rep" },
			[105] = { model = "csb_g", label = "G" },
			[106] = { model = "csb_groom", label = "Groom" },
			[107] = { model = "csb_grove_str_dlr", label = "Grove Str Dlr" },
			[108] = { model = "csb_hao", label = "Hao" },
			[109] = { model = "csb_hugh", label = "Hugh" },
			[110] = { model = "csb_imran", label = "Imran" },
			[111] = { model = "csb_jackhowitzer", label = "Jack Howitzer" },
			[112] = { model = "csb_janitor", label = "Janitor" },
			[113] = { model = "csb_maude", label = "Maude" },
			[114] = { model = "csb_money", label = "Money" },
			[115] = { model = "csb_mp_agent14", label = "MP Agent 14" },
			[116] = { model = "csb_mrs_r", label = "Mrs. R" },
			[117] = { model = "csb_mweather", label = "Mweather" },
			[118] = { model = "csb_ortega", label = "Ortega" },
			[119] = { model = "csb_oscar", label = "Oscar" },
			[120] = { model = "csb_paige", label = "Paige" },
			[121] = { model = "csb_popov", label = "Popov" },
			[122] = { model = "csb_porndudes", label = "Porn Dudes" },
			[123] = { model = "csb_prologuedriver", label = "Prologue Driver" },
			[124] = { model = "csb_prolsec", label = "Prolsec" },
			[125] = { model = "csb_ramp_gang", label = "Ramp Gang" },
			[126] = { model = "csb_ramp_hic", label = "Ramp Hic" },
			[127] = { model = "csb_ramp_hipster", label = "Ramp Hipster" },
			[128] = { model = "csb_ramp_marine", label = "Ramp Marine" },
			[129] = { model = "csb_ramp_mex", label = "Ramp Mex" },
			[130] = { model = "csb_rashcosvki", label = "Rashcosvki" },
			[131] = { model = "csb_reporter", label = "Reporter" },
			[132] = { model = "csb_roccopelosi", label = "Rocco Pelosi" },
			[133] = { model = "csb_screen_writer", label = "Screen Writer" },
			[134] = { model = "csb_sol", label = "Sol" },
			[135] = { model = "csb_stripper_01", label = "Stripper 01" },
			[136] = { model = "csb_stripper_02", label = "Stripper 02" },
			[137] = { model = "csb_talcc", label = "Talcc" },
			[138] = { model = "csb_talmm", label = "Talmm" },
			[139] = { model = "csb_tonya", label = "Tonya" },
			[140] = { model = "csb_tonyprince", label = "Tony Prince" },
			[141] = { model = "csb_trafficwarden", label = "Traffic Warden" },
			[142] = { model = "csb_undercover", label = "Undercover" },
			[143] = { model = "csb_vagspeak", label = "Vagspeak" },
			[144] = { model = "csb_agatha", label = "Agatha" },
			[145] = { model = "csb_avery", label = "Avery" },
			[146] = { model = "csb_brucie2", label = "Brucie 2" },
			[147] = { model = "csb_thornton", label = "Thornton" },
			[148] = { model = "csb_tomcasino", label = "Tom Casino" },
			[149] = { model = "csb_vincent", label = "Vincent" },
		},
	},
	[5] = {
		category = _U("main_personnal_appearance_pedscategory5"),
		models = {
			[1] = { model = "g_f_importexport_01", label = "Import Export 01" },
			[2] = { model = "g_f_y_ballas_01", label = "Ballas 01" },
			[3] = { model = "g_f_y_families_01", label = "Families 01" },
			[4] = { model = "g_f_y_lost_01", label = "Lost 01" },
			[5] = { model = "g_f_y_vagos_01", label = "Vagos 01" },
		},
	},
	[6] = {
		category = _U("main_personnal_appearance_pedscategory6"),
		models = {
			[1] = { model = "g_m_importexport_01", label = "Import Export 01" },
			[2] = { model = "g_m_m_armboss_01", label = "Arm Boss 01" },
			[3] = { model = "g_m_m_armgoon_01", label = "Arm Goon 01" },
			[4] = { model = "g_m_m_armlieut_01", label = "Arm Lieut 01" },
			[5] = { model = "g_m_m_chemwork_01", label = "Chem Work 01" },
			[6] = { model = "g_m_m_chiboss_01", label = "Chi Boss 01" },
			[7] = { model = "g_m_m_chicold_01", label = "Chi Cold 01" },
			[8] = { model = "g_m_m_chigoon_01", label = "Chi Goon 01" },
			[9] = { model = "g_m_m_chigoon_02", label = "Chi Goon 02" },
			[10] = { model = "g_m_m_korboss_01", label = "Kor Boss 01" },
			[11] = { model = "g_m_m_mexboss_01", label = "Mex Boss 01" },
			[12] = { model = "g_m_m_mexboss_02", label = "Mex Boss 02" },
			[13] = { model = "g_m_y_armgoon_02", label = "Arm Goon 02" },
			[14] = { model = "g_m_y_azteca_01", label = "Azteca 01" },
			[15] = { model = "g_m_y_ballaeast_01", label = "Balla East 01" },
			[16] = { model = "g_m_y_ballaorig_01", label = "Balla Orig 01" },
			[17] = { model = "g_m_y_ballasout_01", label = "Balla Sout 01" },
			[18] = { model = "g_m_y_famca_01", label = "Famca 01" },
			[19] = { model = "g_m_y_famdnf_01", label = "Famdnf 01" },
			[20] = { model = "g_m_y_famfor_01", label = "Famfor 01" },
			[21] = { model = "g_m_y_korean_01", label = "Korean 01" },
			[22] = { model = "g_m_y_korean_02", label = "Korean 02" },
			[23] = { model = "g_m_y_korlieut_01", label = "Korlieut 01" },
			[24] = { model = "g_m_y_lost_01", label = "Lost 01" },
			[25] = { model = "g_m_y_lost_02", label = "Lost 02" },
			[26] = { model = "g_m_y_lost_03", label = "Lost 03" },
			[27] = { model = "g_m_y_mexgang_01", label = "Mex Gang 01" },
			[28] = { model = "g_m_y_mexgoon_01", label = "Mex Goon 01" },
			[29] = { model = "g_m_y_mexgoon_02", label = "Mex Goon 02" },
			[30] = { model = "g_m_y_mexgoon_03", label = "Mex Goon 03" },
			[31] = { model = "g_m_y_pologoon_01", label = "Polo Goon 01" },
			[32] = { model = "g_m_y_pologoon_02", label = "Polo Goon 02" },
			[33] = { model = "g_m_y_salvaboss_01", label = "Salva Boss 01" },
			[34] = { model = "g_m_y_salvagoon_01", label = "Salva Goon 01" },
			[35] = { model = "g_m_y_salvagoon_02", label = "Salva Goon 02" },
			[36] = { model = "g_m_y_salvagoon_03", label = "Salva Goon 03" },
			[37] = { model = "g_m_y_strpunk_01", label = "Str Punk 01" },
			[38] = { model = "g_m_y_strpunk_02", label = "Str Punk 02" },
			[39] = { model = "g_m_m_casrn_01", label = "Casrn 01" },
		},
	},
	[7] = {
		category = _U("main_personnal_appearance_pedscategory7"),
		models = {
			[1] = { model = "mp_f_bennymech_01", label = "Benny Mechanic 01" },
			[2] = { model = "mp_f_boatstaff_01", label = "Boat Staff 01" },
			[3] = { model = "mp_f_cardesign_01", label = "Car Design 01" },
			[4] = { model = "mp_f_chbar_01", label = "CH Bar 01" },
			[5] = { model = "mp_f_cocaine_01", label = "Cocaine 01" },
			[6] = { model = "mp_f_counterfeit_01", label = "Counterfeit 01" },
			[7] = { model = "mp_f_deadhooker", label = "Dead Hooker" },
			[8] = { model = "mp_f_execpa_01", label = "Exec PA 01" },
			[9] = { model = "mp_f_execpa_02", label = "Exec PA 02" },
			[10] = { model = "mp_f_forgery_01", label = "Forgery 01" },
			[11] = { model = "mp_f_freemode_01", label = "Freemode 01" },
			[12] = { model = "mp_f_helistaff_01", label = "Heli Staff 01" },
			[13] = { model = "mp_f_meth_01", label = "Meth 01" },
			[14] = { model = "mp_f_misty_01", label = "Misty 01" },
			[15] = { model = "mp_f_stripperlite", label = "Stripperlite" },
			[16] = { model = "mp_f_weed_01", label = "Weed 01" },
			[17] = { model = "mp_g_m_pros_01", label = "Pros 01" },
			[18] = { model = "mp_m_avongoon", label = "Avon Goon" },
			[19] = { model = "mp_m_boatstaff_01", label = "Boat Staff 01" },
			[20] = { model = "mp_m_bogdangoon", label = "Bogdan Goon" },
			[21] = { model = "mp_m_claude_01", label = "Claude 01" },
			[22] = { model = "mp_m_cocaine_01", label = "Cocaine 01" },
			[23] = { model = "mp_m_counterfeit_01", label = "Counterfeit 01" },
			[24] = { model = "mp_m_exarmy_01", label = "Ex Army 01" },
			[25] = { model = "mp_m_execpa_01", label = "Exec PA 01" },
			[26] = { model = "mp_m_famdd_01", label = "Fam DD 01" },
			[27] = { model = "mp_m_fibsec_01", label = "FIB Sec 01" },
			[28] = { model = "mp_m_forgery_01", label = "Forgery 01" },
			[29] = { model = "mp_m_freemode_01", label = "Freemode 01" },
			[30] = { model = "mp_m_g_vagfun_01", label = "Vag Fun 01" },
			[31] = { model = "mp_m_marston_01", label = "Marston 01" },
			[32] = { model = "mp_m_meth_01", label = "Meth 01" },
			[33] = { model = "mp_m_niko_01", label = "Niko 01" },
			[34] = { model = "mp_m_securoguard_01", label = "Securo Guard 01" },
			[35] = { model = "mp_m_shopkeep_01", label = "Shopkeep 01" },
			[36] = { model = "mp_m_waremech_01", label = "Ware Mech 01" },
			[37] = { model = "mp_m_weapexp_01", label = "Weap Exp 01" },
			[38] = { model = "mp_m_weapwork_01", label = "Weap Work 01" },
			[39] = { model = "mp_m_weed_01", label = "Weed 01" },
			[40] = { model = "mp_s_m_armoured_01", label = "Armoured 01" },
		},
	},
	[8] = {
		category = _U("main_personnal_appearance_pedscategory8"),
		models = {
			[1] = { model = "s_f_m_fembarber", label = "Female Barber" },
			[2] = { model = "s_f_m_maid_01", label = "Maid 01" },
			[3] = { model = "s_f_m_shop_high", label = "Shop High" },
			[4] = { model = "s_f_m_sweatshop_01", label = "Sweatshop 01" },
			[5] = { model = "s_f_y_airhostess_01", label = "Air Hostess 01" },
			[6] = { model = "s_f_y_bartender_01", label = "Bartender 01" },
			[7] = { model = "s_f_y_baywatch_01", label = "Baywatch 01" },
			[8] = { model = "s_f_y_clubbar_01", label = "Club Bar 01" },
			[9] = { model = "s_f_y_cop_01", label = "Cop 01" },
			[10] = { model = "s_f_y_factory_01", label = "Factory 01" },
			[11] = { model = "s_f_y_hooker_01", label = "Hooker 01" },
			[12] = { model = "s_f_y_hooker_02", label = "Hooker 02" },
			[13] = { model = "s_f_y_hooker_03", label = "Hooker 03" },
			[14] = { model = "s_f_y_migrant_01", label = "Migrant 01" },
			[15] = { model = "s_f_y_movprem_01", label = "Movprem 01" },
			[16] = { model = "s_f_y_ranger_01", label = "Ranger 01" },
			[17] = { model = "s_f_y_scrubs_01", label = "Scrubs 01" },
			[18] = { model = "s_f_y_sheriff_01", label = "Sheriff 01" },
			[19] = { model = "s_f_y_shop_low", label = "Shop Low" },
			[20] = { model = "s_f_y_shop_mid", label = "Shop Mid" },
			[21] = { model = "s_f_y_stripper_01", label = "Stripper 01" },
			[22] = { model = "s_f_y_stripper_02", label = "Stripper 02" },
			[23] = { model = "s_f_y_stripperlite", label = "Stripperlite" },
			[24] = { model = "s_f_y_sweatshop_01", label = "Sweatshop 01" },
			[25] = { model = "s_f_y_casino_01", label = "Casino 01" },
		},
	},
	[9] = {
		category = _U("main_personnal_appearance_pedscategory9"),
		models = {
			[1] = { model = "s_m_m_ammucountry", label = "Ammu-Nation Country" },
			[2] = { model = "s_m_m_armoured_01", label = "Armoured 01" },
			[3] = { model = "s_m_m_armoured_02", label = "Armoured 02" },
			[4] = { model = "s_m_m_autoshop_01", label = "Autoshop 01" },
			[5] = { model = "s_m_m_autoshop_02", label = "Autoshop 02" },
			[6] = { model = "s_m_m_bouncer_01", label = "Bouncer 01" },
			[7] = { model = "s_m_m_ccrew_01", label = "CCrew 01" },
			[8] = { model = "s_m_m_chemsec_01", label = "Chemsec 01" },
			[9] = { model = "s_m_m_ciasec_01", label = "CIASec 01" },
			[10] = { model = "s_m_m_cntrybar_01", label = "Cntrybar 01" },
			[11] = { model = "s_m_m_dockwork_01", label = "Dockwork 01" },
			[12] = { model = "s_m_m_doctor_01", label = "Doctor 01" },
			[13] = { model = "s_m_m_fiboffice_01", label = "FIB Office 01" },
			[14] = { model = "s_m_m_fiboffice_02", label = "FIB Office 02" },
			[15] = { model = "s_m_m_fibsec_01", label = "FIB Security 01" },
			[16] = { model = "s_m_m_gaffer_01", label = "Gaffer 01" },
			[17] = { model = "s_m_m_gardener_01", label = "Gardener 01" },
			[18] = { model = "s_m_m_gentransport", label = "Gentransport" },
			[19] = { model = "s_m_m_hairdress_01", label = "Hairdress 01" },
			[20] = { model = "s_m_m_highsec_01", label = "Highsec 01" },
			[21] = { model = "s_m_m_highsec_02", label = "Highsec 02" },
			[22] = { model = "s_m_m_janitor", label = "Janitor" },
			[23] = { model = "s_m_m_lathandy_01", label = "Lathandy 01" },
			[24] = { model = "s_m_m_lifeinvad_01", label = "Lifeinvader 01" },
			[25] = { model = "s_m_m_linecook", label = "Linecook" },
			[26] = { model = "s_m_m_lsmetro_01", label = "LS Metro 01" },
			[27] = { model = "s_m_m_mariachi_01", label = "Mariachi 01" },
			[28] = { model = "s_m_m_marine_01", label = "Marine 01" },
			[29] = { model = "s_m_m_marine_02", label = "Marine 02" },
			[30] = { model = "s_m_m_migrant_01", label = "Migrant 01" },
			[31] = { model = "s_m_m_movalien_01", label = "Movalien 01" },
			[32] = { model = "s_m_m_movprem_01", label = "Movprem 01" },
			[33] = { model = "s_m_m_movspace_01", label = "Movspace 01" },
			[34] = { model = "s_m_m_paramedic_01", label = "Paramedic 01" },
			[35] = { model = "s_m_m_pilot_01", label = "Pilot 01" },
			[36] = { model = "s_m_m_pilot_02", label = "Pilot 02" },
			[37] = { model = "s_m_m_postal_01", label = "Postal 01" },
			[38] = { model = "s_m_m_postal_02", label = "Postal 02" },
			[39] = { model = "s_m_m_prisguard_01", label = "Prison Guard 01" },
			[40] = { model = "s_m_m_scientist_01", label = "Scientist 01" },
			[41] = { model = "s_m_m_security_01", label = "Security 01" },
			[42] = { model = "s_m_m_snowcop_01", label = "Snow Cop 01" },
			[43] = { model = "s_m_m_strperf_01", label = "Strperf 01" },
			[44] = { model = "s_m_m_strpreach_01", label = "Strpreach 01" },
			[45] = { model = "s_m_m_strvend_01", label = "Strvend 01" },
			[46] = { model = "s_m_m_trucker_01", label = "Trucker 01" },
			[47] = { model = "s_m_m_ups_01", label = "UPS 01" },
			[48] = { model = "s_m_m_ups_02", label = "UPS 02" },
			[49] = { model = "s_m_o_busker_01", label = "Busker 01" },
			[50] = { model = "s_m_y_airworker", label = "Air Worker" },
			[51] = { model = "s_m_y_ammucity_01", label = "Ammu-Nation City 01" },
			[52] = { model = "s_m_y_armymech_01", label = "Army Mechanic 01" },
			[53] = { model = "s_m_y_autopsy_01", label = "Autopsy 01" },
			[54] = { model = "s_m_y_barman_01", label = "Barman 01" },
			[55] = { model = "s_m_y_baywatch_01", label = "Baywatch 01" },
			[56] = { model = "s_m_y_blackops_01", label = "Black Ops 01" },
			[57] = { model = "s_m_y_blackops_02", label = "Black Ops 02" },
			[58] = { model = "s_m_y_blackops_03", label = "Black Ops 03" },
			[59] = { model = "s_m_y_busboy_01", label = "Busboy 01" },
			[60] = { model = "s_m_y_chef_01", label = "Chef 01" },
			[61] = { model = "s_m_y_clown_01", label = "Clown 01" },
			[62] = { model = "s_m_y_clubbar_01", label = "Club Bar 01" },
			[63] = { model = "s_m_y_construct_01", label = "Construct 01" },
			[64] = { model = "s_m_y_construct_02", label = "Construct 02" },
			[65] = { model = "s_m_y_cop_01", label = "Cop 01" },
			[66] = { model = "s_m_y_dealer_01", label = "Dealer 01" },
			[67] = { model = "s_m_y_devinsec_01", label = "Devin Security 01" },
			[68] = { model = "s_m_y_dockwork_01", label = "Dockwork 01" },
			[69] = { model = "s_m_y_doorman_01", label = "Doorman 01" },
			[70] = { model = "s_m_y_dwservice_01", label = "Dw Service 01" },
			[71] = { model = "s_m_y_dwservice_02", label = "Dw Service 02" },
			[72] = { model = "s_m_y_factory_01", label = "Factory 01" },
			[73] = { model = "s_m_y_fireman_01", label = "Fireman 01" },
			[74] = { model = "s_m_y_garbage", label = "Garbage" },
			[75] = { model = "s_m_y_grip_01", label = "Grip 01" },
			[76] = { model = "s_m_y_hwaycop_01", label = "Highway Cop 01" },
			[77] = { model = "s_m_y_marine_01", label = "Marine 01" },
			[78] = { model = "s_m_y_marine_02", label = "Marine 02" },
			[79] = { model = "s_m_y_marine_03", label = "Marine 03" },
			[80] = { model = "s_m_y_mime", label = "Mime" },
			[81] = { model = "s_m_y_pestcont_01", label = "Pest Control 01" },
			[82] = { model = "s_m_y_pilot_01", label = "Pilot 01" },
			[83] = { model = "s_m_y_prismuscl_01", label = "Prismuscl 01" },
			[84] = { model = "s_m_y_prisoner_01", label = "Prisoner 01" },
			[85] = { model = "s_m_y_ranger_01", label = "Ranger 01" },
			[86] = { model = "s_m_y_robber_01", label = "Robber 01" },
			[87] = { model = "s_m_y_sheriff_01", label = "Sheriff 01" },
			[88] = { model = "s_m_y_shop_mask", label = "Shop Mask" },
			[89] = { model = "s_m_y_strvend_01", label = "Strvend 01" },
			[90] = { model = "s_m_y_swat_01", label = "SWAT 01" },
			[91] = { model = "s_m_y_uscg_01", label = "US Coast Guard 01" },
			[92] = { model = "s_m_y_valet_01", label = "Valet 01" },
			[93] = { model = "s_m_y_waiter_01", label = "Waiter 01" },
			[94] = { model = "s_m_y_waretech_01", label = "Waretech 01" },
			[95] = { model = "s_m_y_winclean_01", label = "Winclean 01" },
			[96] = { model = "s_m_y_xmech_01", label = "Xmech 01" },
			[97] = { model = "s_m_y_xmech_02", label = "Xmech 02" },
			[98] = { model = "s_m_y_casino_01", label = "Casino 01" },
			[99] = { model = "s_m_y_westsec_01", label = "West Security 01" },
		},
	},
	[10] = {
		category = _U("main_personnal_appearance_pedscategory10"),
		models = {
			[1] = { model = "hc_driver", label = "Driver" },
			[2] = { model = "hc_gunman", label = "Gunman" },
			[3] = { model = "hc_hacker", label = "Hacker" },
			[4] = { model = "ig_abigail", label = "Abigail" },
			[5] = { model = "ig_agent", label = "Agent" },
			[6] = { model = "ig_amandatownley", label = "Amanda Townley" },
			[7] = { model = "ig_andreas", label = "Andreas" },
			[8] = { model = "ig_ashley", label = "Ashley" },
			[9] = { model = "ig_avon", label = "Avon" },
			[10] = { model = "ig_ballasog", label = "Ballas OG" },
			[11] = { model = "ig_bankman", label = "Bankman" },
			[12] = { model = "ig_barry", label = "Barry" },
			[13] = { model = "ig_benny", label = "Benny" },
			[14] = { model = "ig_bestmen", label = "Bestmen" },
			[15] = { model = "ig_beverly", label = "Beverly" },
			[16] = { model = "ig_brad", label = "Brad" },
			[17] = { model = "ig_bride", label = "Bride" },
			[18] = { model = "ig_car3guy1", label = "Car3guy1" },
			[19] = { model = "ig_car3guy2", label = "Car3guy2" },
			[20] = { model = "ig_casey", label = "Casey" },
			[21] = { model = "ig_chef", label = "Chef" },
			[22] = { model = "ig_chef2", label = "Chef2" },
			[23] = { model = "ig_chengsr", label = "Cheng SR" },
			[24] = { model = "ig_chrisformage", label = "Chris Formage" },
			[25] = { model = "ig_clay", label = "Clay" },
			[26] = { model = "ig_claypain", label = "Claypain" },
			[27] = { model = "ig_cletus", label = "Cletus" },
			[28] = { model = "ig_dale", label = "Dale" },
			[29] = { model = "ig_davenorton", label = "Dave Norton" },
			[30] = { model = "ig_denise", label = "Denise" },
			[31] = { model = "ig_devin", label = "Devin" },
			[32] = { model = "ig_dix", label = "Dix" },
			[33] = { model = "ig_djblamadon", label = "DJ Blamadon" },
			[34] = { model = "ig_djblamrupert", label = "DJ Blamrupert" },
			[35] = { model = "ig_djblamryans", label = "DJ Blamryans" },
			[36] = { model = "ig_djdixmanager", label = "DJ Dix Manager" },
			[37] = { model = "ig_djgeneric_01", label = "DJ Generic 01" },
			[38] = { model = "ig_djsolfotios", label = "DJ Solfotios" },
			[39] = { model = "ig_djsoljakob", label = "DJ Soljakob" },
			[40] = { model = "ig_djsolmanager", label = "DJ Sol Manager" },
			[41] = { model = "ig_djsolmike", label = "DJ Solmike" },
			[42] = { model = "ig_djsolrobt", label = "DJ Solrobt" },
			[43] = { model = "ig_djtalaurelia", label = "DJ Talaurelia" },
			[44] = { model = "ig_djtalignazio", label = "DJ Talignazio" },
			[45] = { model = "ig_dom", label = "Dom" },
			[46] = { model = "ig_dreyfuss", label = "Dreyfuss" },
			[47] = { model = "ig_drfriedlander", label = "Dr. Friedlander" },
			[48] = { model = "ig_englishdave", label = "English Dave" },
			[49] = { model = "ig_fabien", label = "Fabien" },
			[50] = { model = "ig_fbisuit_01", label = "FBI Suit 01" },
			[51] = { model = "ig_floyd", label = "Floyd" },
			[52] = { model = "ig_g", label = "G" },
			[53] = { model = "ig_groom", label = "Groom" },
			[54] = { model = "ig_hao", label = "Hao" },
			[55] = { model = "ig_hunter", label = "Hunter" },
			[56] = { model = "ig_janet", label = "Janet" },
			[57] = { model = "ig_jay_norris", label = "Jay Norris" },
			[58] = { model = "ig_jewelass", label = "Jewelass" },
			[59] = { model = "ig_jimmyboston", label = "Jimmy Boston" },
			[60] = { model = "ig_jimmyboston_02", label = "Jimmy Boston 02" },
			[61] = { model = "ig_jimmydisanto", label = "Jimmy De Santa" },
			[62] = { model = "ig_joeminuteman", label = "Joe Minuteman" },
			[63] = { model = "ig_johnnyklebitz", label = "Johnny Klebitz" },
			[64] = { model = "ig_josef", label = "Josef" },
			[65] = { model = "ig_josh", label = "Josh" },
			[66] = { model = "ig_karen_daniels", label = "Karen Daniels" },
			[67] = { model = "ig_kerrymcintosh", label = "Kerry McIntosh" },
			[68] = { model = "ig_kerrymcintosh_02", label = "Kerry McIntosh 02" },
			[69] = { model = "ig_lacey_jones_02", label = "Lacey Jones 02" },
			[70] = { model = "ig_lamardavis", label = "Lamar Davis" },
			[71] = { model = "ig_lazlow", label = "Lazlow" },
			[72] = { model = "ig_lazlow_2", label = "Lazlow 2" },
			[73] = { model = "ig_lestercrest", label = "Lester Crest" },
			[74] = { model = "ig_lestercrest_2", label = "Lester Crest 2" },
			[75] = { model = "ig_lifeinvad_01", label = "Lifeinvad 01" },
			[76] = { model = "ig_lifeinvad_02", label = "Lifeinvad 02" },
			[77] = { model = "ig_magenta", label = "Magenta" },
			[78] = { model = "ig_malc", label = "Malc" },
			[79] = { model = "ig_manuel", label = "Manuel" },
			[80] = { model = "ig_marnie", label = "Marnie" },
			[81] = { model = "ig_maryann", label = "Mary Ann" },
			[82] = { model = "ig_maude", label = "Maude" },
			[83] = { model = "ig_michelle", label = "Michelle" },
			[84] = { model = "ig_milton", label = "Milton" },
			[85] = { model = "ig_molly", label = "Molly" },
			[86] = { model = "ig_money", label = "Money" },
			[87] = { model = "ig_mp_agent14", label = "MP Agent 14" },
			[88] = { model = "ig_mrk", label = "Mr. K" },
			[89] = { model = "ig_mrs_thornhill", label = "Mrs. Thornhill" },
			[90] = { model = "ig_mrsphillips", label = "Mrs. Phillips" },
			[91] = { model = "ig_natalia", label = "Natalia" },
			[92] = { model = "ig_nervousron", label = "Nervous Ron" },
			[93] = { model = "ig_nigel", label = "Nigel" },
			[94] = { model = "ig_old_man1a", label = "Old Man 1A" },
			[95] = { model = "ig_old_man2", label = "Old Man 2" },
			[96] = { model = "ig_omega", label = "Omega" },
			[97] = { model = "ig_oneil", label = "O'Neil" },
			[98] = { model = "ig_orleans", label = "Orleans" },
			[99] = { model = "ig_ortega", label = "Ortega" },
			[100] = { model = "ig_paige", label = "Paige" },
			[101] = { model = "ig_paper", label = "Paper" },
			[102] = { model = "ig_patricia", label = "Patricia" },
			[103] = { model = "ig_popov", label = "Popov" },
			[104] = { model = "ig_priest", label = "Priest" },
			[105] = { model = "ig_prolsec_02", label = "Prolsec 02" },
			[106] = { model = "ig_ramp_gang", label = "Ramp Gang" },
			[107] = { model = "ig_ramp_hic", label = "Ramp Hic" },
			[108] = { model = "ig_ramp_hipster", label = "Ramp Hipster" },
			[109] = { model = "ig_ramp_mex", label = "Ramp Mex" },
			[110] = { model = "ig_rashcosvki", label = "Rashcosvki" },
			[111] = { model = "ig_roccopelosi", label = "Rocco Pelosi" },
			[112] = { model = "ig_russiandrunk", label = "Russian Drunk" },
			[113] = { model = "ig_sacha", label = "Sacha" },
			[114] = { model = "ig_screen_writer", label = "Screen Writer" },
			[115] = { model = "ig_siemonyetarian", label = "Siemonyetarian" },
			[116] = { model = "ig_sol", label = "Sol" },
			[117] = { model = "ig_solomon", label = "Solomon" },
			[118] = { model = "ig_stevehains", label = "Steve Hains" },
			[119] = { model = "ig_stretch", label = "Stretch" },
			[120] = { model = "ig_talcc", label = "Talcc" },
			[121] = { model = "ig_talina", label = "Talina" },
			[122] = { model = "ig_talmm", label = "Talmm" },
			[123] = { model = "ig_tanisha", label = "Tanisha" },
			[124] = { model = "ig_taocheng", label = "Tao Cheng" },
			[125] = { model = "ig_taostranslator", label = "Tao's Translator" },
			[126] = { model = "ig_tenniscoach", label = "Tennis Coach" },
			[127] = { model = "ig_terry", label = "Terry" },
			[128] = { model = "ig_tomepsilon", label = "Tom Epsilon" },
			[129] = { model = "ig_tonya", label = "Tonya" },
			[130] = { model = "ig_tonyprince", label = "Tony Prince" },
			[131] = { model = "ig_tracydisanto", label = "Tracy De Santa" },
			[132] = { model = "ig_trafficwarden", label = "Traffic Warden" },
			[133] = { model = "ig_tylerdix", label = "Tyler Dix" },
			[134] = { model = "ig_tylerdix_02", label = "Tyler Dix 02" },
			[135] = { model = "ig_vagspeak", label = "Vagos Speak" },
			[136] = { model = "ig_wade", label = "Wade" },
			[137] = { model = "ig_zimbor", label = "Zimbor" },
			[138] = { model = "player_one", label = "Player One" },
			[139] = { model = "player_two", label = "Player Two" },
			[140] = { model = "player_zero", label = "Player Zero" },
			[141] = { model = "ig_agatha", label = "Agatha" },
			[142] = { model = "ig_avery", label = "Avery" },
			[143] = { model = "ig_brucie2", label = "Brucie 2" },
			[144] = { model = "ig_thornton", label = "Thornton" },
			[145] = { model = "ig_tomcasino", label = "Tom Casino" },
			[146] = { model = "ig_vincent", label = "Vincent" },
		},
	},
	[11] = {
		category = _U("main_personnal_appearance_pedscategory11"),
		models = {
			[1] = { model = "u_f_m_corpse_01", label = "Corpse 01" },
			[2] = { model = "u_f_m_miranda", label = "Miranda" },
			[3] = { model = "u_f_m_miranda_02", label = "Miranda 02" },
			[4] = { model = "u_f_m_promourn_01", label = "Promourn 01" },
			[5] = { model = "u_f_o_moviestar", label = "Moviestar" },
			[6] = { model = "u_f_o_prolhost_01", label = "Prolhost 01" },
			[7] = { model = "u_f_y_bikerchic", label = "Bikerchic" },
			[8] = { model = "u_f_y_comjane", label = "Comjane" },
			[9] = { model = "u_f_y_corpse_01", label = "Corpse 01" },
			[10] = { model = "u_f_y_corpse_02", label = "Corpse 02" },
			[11] = { model = "u_f_y_danceburl_01", label = "Danceburl 01" },
			[12] = { model = "u_f_y_dancelthr_01", label = "Dancelthr 01" },
			[13] = { model = "u_f_y_dancerave_01", label = "Dancerave 01" },
			[14] = { model = "u_f_y_hotposh_01", label = "Hotposh 01" },
			[15] = { model = "u_f_y_jewelass_01", label = "Jewelass 01" },
			[16] = { model = "u_f_y_mistress", label = "Mistress" },
			[17] = { model = "u_f_y_poppymich", label = "Poppymich" },
			[18] = { model = "u_f_y_poppymich_02", label = "Poppymich 02" },
			[19] = { model = "u_f_y_princess", label = "Princess" },
			[20] = { model = "u_f_y_spyactress", label = "Spyactress" },
			[21] = { model = "u_f_m_casinocash_01", label = "Casinocash 01" },
			[22] = { model = "u_f_m_casinoshop_01", label = "Casinoshop 01" },
			[23] = { model = "u_f_m_debbie_01", label = "Debbie 01" },
			[24] = { model = "u_f_o_carol", label = "Carol" },
			[25] = { model = "u_f_o_eileen", label = "Eileen" },
			[26] = { model = "u_f_y_beth", label = "Beth" },
			[27] = { model = "u_f_y_lauren", label = "Lauren" },
			[28] = { model = "u_f_y_taylor", label = "Taylor" },
		},
	},
	[12] = {
		category = _U("main_personnal_appearance_pedscategory12"),
		models = {
			[1] = { model = "u_m_m_aldinapoli", label = "Aldinapoli" },
			[2] = { model = "u_m_m_bankman", label = "Bankman" },
			[3] = { model = "u_m_m_bikehire_01", label = "Bikehire 01" },
			[4] = { model = "u_m_m_doa_01", label = "Doa 01" },
			[5] = { model = "u_m_m_edtoh", label = "Edtoh" },
			[6] = { model = "u_m_m_fibarchitect", label = "Fibarchitect" },
			[7] = { model = "u_m_m_filmdirector", label = "Filmdirector" },
			[8] = { model = "u_m_m_glenstank_01", label = "Glenstank 01" },
			[9] = { model = "u_m_m_griff_01", label = "Griff 01" },
			[10] = { model = "u_m_m_jesus_01", label = "Jesus 01" },
			[11] = { model = "u_m_m_jewelsec_01", label = "Jewelsec 01" },
			[12] = { model = "u_m_m_jewelthief", label = "Jewelthief" },
			[13] = { model = "u_m_m_markfost", label = "Markfost" },
			[14] = { model = "u_m_m_partytarget", label = "Partytarget" },
			[15] = { model = "u_m_m_prolsec_01", label = "Prolsec 01" },
			[16] = { model = "u_m_m_promourn_01", label = "Promourn 01" },
			[17] = { model = "u_m_m_rivalpap", label = "Rivalpap" },
			[18] = { model = "u_m_m_spyactor", label = "Spyactor" },
			[19] = { model = "u_m_m_streetart_01", label = "Streetart 01" },
			[20] = { model = "u_m_m_willyfist", label = "Willyfist" },
			[21] = { model = "u_m_o_filmnoir", label = "Filmnoir" },
			[22] = { model = "u_m_o_finguru_01", label = "Finguru 01" },
			[23] = { model = "u_m_o_taphillbilly", label = "Taphillbilly" },
			[24] = { model = "u_m_o_tramp_01", label = "Tramp 01" },
			[25] = { model = "u_m_y_abner", label = "Abner" },
			[26] = { model = "u_m_y_antonb", label = "Antonb" },
			[27] = { model = "u_m_y_babyd", label = "Babyd" },
			[28] = { model = "u_m_y_baygor", label = "Baygor" },
			[29] = { model = "u_m_y_burgerdrug_01", label = "Burgerdrug 01" },
			[30] = { model = "u_m_y_chip", label = "Chip" },
			[31] = { model = "u_m_y_corpse_01", label = "Corpse 01" },
			[32] = { model = "u_m_y_cyclist_01", label = "Cyclist 01" },
			[33] = { model = "u_m_y_danceburl_01", label = "Danceburl 01" },
			[34] = { model = "u_m_y_dancelthr_01", label = "Dancelthr 01" },
			[35] = { model = "u_m_y_dancerave_01", label = "Dancerave 01" },
			[36] = { model = "u_m_y_fibmugger_01", label = "Fibmugger 01" },
			[37] = { model = "u_m_y_guido_01", label = "Guido 01" },
			[38] = { model = "u_m_y_gunvend_01", label = "Gunvend 01" },
			[39] = { model = "u_m_y_hippie_01", label = "Hippie 01" },
			[40] = { model = "u_m_y_imporage", label = "Imporage" },
			[41] = { model = "u_m_y_juggernaut_01", label = "Juggernaut 01" },
			[42] = { model = "u_m_y_justin", label = "Justin" },
			[43] = { model = "u_m_y_mani", label = "Mani" },
			[44] = { model = "u_m_y_militarybum", label = "Militarybum" },
			[45] = { model = "u_m_y_paparazzi", label = "Paparazzi" },
			[46] = { model = "u_m_y_party_01", label = "Party 01" },
			[47] = { model = "u_m_y_pogo_01", label = "Pogo 01" },
			[48] = { model = "u_m_y_prisoner_01", label = "Prisoner 01" },
			[49] = { model = "u_m_y_proldriver_01", label = "Proldriver 01" },
			[50] = { model = "u_m_y_rsranger_01", label = "Rsranger 01" },
			[51] = { model = "u_m_y_sbike", label = "Sbike" },
			[52] = { model = "u_m_y_smugmech_01", label = "Smugmech 01" },
			[53] = { model = "u_m_y_staggrm_01", label = "Staggrm 01" },
			[54] = { model = "u_m_y_tattoo_01", label = "Tattoo 01" },
			[55] = { model = "u_m_y_zombie_01", label = "Zombie 01" },
			[56] = { model = "u_m_m_blane", label = "Blane" },
			[57] = { model = "u_m_m_curtis", label = "Curtis" },
			[58] = { model = "u_m_m_vince", label = "Vince" },
			[59] = { model = "u_m_o_dean", label = "Dean" },
			[60] = { model = "u_m_y_caleb", label = "Caleb" },
			[61] = { model = "u_m_y_croupthief_01", label = "Croupthief 01" },
			[62] = { model = "u_m_y_gabriel", label = "Gabriel" },
			[63] = { model = "u_m_y_ushi", label = "Ushi" },
		},
	},
}
